//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAR_CORR_RELA_BackUp20180609
    {
        public int AUTO_ID { get; set; }
        public string ADDR { get; set; }
        public string PCB_CODE { get; set; }
        public string PAN_CODE { get; set; }
        public string CUSTOM_CODE { get; set; }
        public Nullable<int> CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string ORDER_ID { get; set; }
        public Nullable<int> METER_ID { get; set; }
        public string DEPART_ID { get; set; }
        public string PAN_CODE_ADDR { get; set; }
        public string CUSTOM_CODE_ADDR { get; set; }
        public Nullable<int> CUSTOM_CODE_UPDATE_ID { get; set; }
        public Nullable<System.DateTime> CUSTOM_CODE_UPDATE_DATE { get; set; }
        public string PCB_ADDR { get; set; }
    }
}
