//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidDatas
    {
        public int AutoID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string BidName { get; set; }
        public Nullable<decimal> BidPrice { get; set; }
        public string PackageNo { get; set; }
        public string ProgramUnit { get; set; }
        public string GoodsName { get; set; }
        public string TotalNum { get; set; }
        public string UnitPrice { get; set; }
        public string BasePrice { get; set; }
        public string Score { get; set; }
        public string BidContent { get; set; }
    }
}
