//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxInfor
    {
        public string ht_code { get; set; }
        public string b_area { get; set; }
        public string b_type { get; set; }
        public string cur_volt { get; set; }
        public string b_order { get; set; }
        public string meter_sum { get; set; }
        public string txm_start { get; set; }
        public string txm_end { get; set; }
        public string box_capacity { get; set; }
        public string box_sum { get; set; }
        public string o_date { get; set; }
        public string o_operator { get; set; }
        public string bz { get; set; }
        public string real_txmstart { get; set; }
        public string real_txmlen { get; set; }
        public string last_box_valu { get; set; }
        public string boxcode_bz { get; set; }
        public string Scodenum { get; set; }
        public string nowcode { get; set; }
        public string pastcode { get; set; }
        public string past_bz { get; set; }
        public string pastblocks { get; set; }
        public string pastcode1 { get; set; }
        public string pastblocks1 { get; set; }
        public string pastcode2 { get; set; }
        public string pastblocks2 { get; set; }
        public string pastcode3 { get; set; }
        public string pastblocks3 { get; set; }
        public string pastcode4 { get; set; }
        public string pastblocks4 { get; set; }
        public string pastcode5 { get; set; }
        public string pastblocks5 { get; set; }
        public string pastcode6 { get; set; }
        public string pastblocks6 { get; set; }
        public string pastcode7 { get; set; }
        public string pastblocks7 { get; set; }
        public string pasttxm { get; set; }
        public string pasttxm1 { get; set; }
        public string pasttxm2 { get; set; }
        public string pasttxm3 { get; set; }
        public string pasttxm4 { get; set; }
        public string pasttxm5 { get; set; }
        public string pasttxm6 { get; set; }
        public string pasttxm7 { get; set; }
        public string validate { get; set; }
    }
}
