//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEH_BAR_CORR_RELA
    {
        public int ID { get; set; }
        public string order_ID { get; set; }
        public string pan_code { get; set; }
        public string pan_code_addr { get; set; }
        public Nullable<int> Status { get; set; }
        public string Device_curr { get; set; }
        public string Total_curr { get; set; }
        public Nullable<int> Create_ID { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
    }
}
