//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CESHI_OUT
    {
        public int Auto_ID { get; set; }
        public string Order_ID { get; set; }
        public string Meter_Name { get; set; }
        public string Meter_No { get; set; }
        public System.DateTime Create_date { get; set; }
        public string Reason { get; set; }
    }
}
