//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CESHI_SUCCESS_LIB20160101
    {
        public string Order_id { get; set; }
        public string meter_id { get; set; }
        public string meter_name { get; set; }
        public string commu_address { get; set; }
        public string depart_id { get; set; }
        public string creat_id { get; set; }
        public Nullable<System.DateTime> creat_time { get; set; }
    }
}
