//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMD_DATANAME
    {
        public int ID { get; set; }
        public string CMD_ID { get; set; }
        public string CMD_CODE { get; set; }
        public string CMD_NAME { get; set; }
        public string DATA_NAME { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
