//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMD_INFO
    {
        public int CMD_ID { get; set; }
        public string CODE_NAME { get; set; }
        public string CMD_NAME { get; set; }
        public string CONTR_CODE { get; set; }
        public string BACK_FLAG { get; set; }
        public string CMD_CODE { get; set; }
        public Nullable<int> DATA_LEN { get; set; }
        public string DATA_FORMAT { get; set; }
        public string RW_FLAG { get; set; }
        public Nullable<int> PASS_EXSI { get; set; }
        public Nullable<int> OPER_EXSI { get; set; }
        public Nullable<int> SHOW_FLAG { get; set; }
        public Nullable<int> READ_FLAG { get; set; }
        public Nullable<int> RS_WAIT { get; set; }
        public Nullable<int> CARR_WAIT { get; set; }
        public Nullable<int> COMM_INTER { get; set; }
        public string CONT_TYPE { get; set; }
        public string CONT_NAME { get; set; }
        public Nullable<int> CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string FIXEDVALUE { get; set; }
        public string UNIVTABLENO { get; set; }
        public string DATA_TYPE { get; set; }
        public string ItemIndex { get; set; }
        public Nullable<int> SubStartPos { get; set; }
        public Nullable<int> SubLength { get; set; }
    }
}
