//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_RULES_BackUp
    {
        public int AUTO_ID { get; set; }
        public string METER_TYPE { get; set; }
        public string ADDR_NAME { get; set; }
        public Nullable<int> ZLEN_NUM { get; set; }
        public string RULES { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string ClientIP { get; set; }
        public Nullable<System.DateTime> VisitTime { get; set; }
    }
}
