//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataForPack
    {
        public int ID { get; set; }
        public string OI { get; set; }
        public string OINAME { get; set; }
        public string ATTRIBUTE { get; set; }
        public string field0Name { get; set; }
        public string field0Len { get; set; }
        public string field0Type { get; set; }
        public string field0Value { get; set; }
        public string field0Default { get; set; }
        public string field0Format { get; set; }
        public string field0Index { get; set; }
        public string field1Name { get; set; }
        public string field1Len { get; set; }
        public string field1Type { get; set; }
        public string field1Value { get; set; }
        public string field1Default { get; set; }
        public string field1Format { get; set; }
        public string field1Index { get; set; }
        public string field2Name { get; set; }
        public string field2Len { get; set; }
        public string field2Type { get; set; }
        public string field2Value { get; set; }
        public string field2Default { get; set; }
        public string field2Format { get; set; }
        public string field2Index { get; set; }
        public string field3Name { get; set; }
        public string field3Len { get; set; }
        public string field3Type { get; set; }
        public string field3Value { get; set; }
        public string field3Default { get; set; }
        public string field3Format { get; set; }
        public string field3Index { get; set; }
        public string IS_ACTIVE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> SELECTED { get; set; }
        public string DATASTR { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
