//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Compare
    {
        public string Meter_Type { get; set; }
        public string ID { get; set; }
        public string up_1 { get; set; }
        public string low_1 { get; set; }
        public string status_1 { get; set; }
        public string up_2 { get; set; }
        public string low_2 { get; set; }
        public string status_2 { get; set; }
        public string up_3 { get; set; }
        public string low_3 { get; set; }
        public string status_3 { get; set; }
        public string up_4 { get; set; }
        public string low_4 { get; set; }
        public string status_4 { get; set; }
        public string up_5 { get; set; }
        public string low_5 { get; set; }
        public string status_5 { get; set; }
        public string up_6 { get; set; }
        public string low_6 { get; set; }
        public string status_6 { get; set; }
        public string up_7 { get; set; }
        public string low_7 { get; set; }
        public string status_7 { get; set; }
        public string up_8 { get; set; }
        public string low_8 { get; set; }
        public string status_8 { get; set; }
        public string up_9 { get; set; }
        public string low_9 { get; set; }
        public string status_9 { get; set; }
        public string up_10 { get; set; }
        public string low_10 { get; set; }
        public string status_10 { get; set; }
        public string up_11 { get; set; }
        public string low_11 { get; set; }
        public string status_11 { get; set; }
        public string up_12 { get; set; }
        public string low_12 { get; set; }
        public string status_12 { get; set; }
        public string up_13 { get; set; }
        public string low_13 { get; set; }
        public string status_13 { get; set; }
        public string up_14 { get; set; }
        public string low_14 { get; set; }
        public string status_14 { get; set; }
        public string up_15 { get; set; }
        public string low_15 { get; set; }
        public string status_15 { get; set; }
        public string up_16 { get; set; }
        public string low_16 { get; set; }
        public string status_16 { get; set; }
        public string up_17 { get; set; }
        public string low_17 { get; set; }
        public string status_17 { get; set; }
        public string up_18 { get; set; }
        public string low_18 { get; set; }
        public string status_18 { get; set; }
        public string up_19 { get; set; }
        public string low_19 { get; set; }
        public string status_19 { get; set; }
        public string up_20 { get; set; }
        public string low_20 { get; set; }
        public string status_20 { get; set; }
        public string up_21 { get; set; }
        public string low_21 { get; set; }
        public string status_21 { get; set; }
        public string up_22 { get; set; }
        public string low_22 { get; set; }
        public string status_22 { get; set; }
        public string up_23 { get; set; }
        public string low_23 { get; set; }
        public string status_23 { get; set; }
        public string up_24 { get; set; }
        public string low_24 { get; set; }
        public string status_24 { get; set; }
        public string up_25 { get; set; }
        public string low_25 { get; set; }
        public string status_25 { get; set; }
        public string up_26 { get; set; }
        public string low_26 { get; set; }
        public string status_26 { get; set; }
        public string up_27 { get; set; }
        public string low_27 { get; set; }
        public string status_27 { get; set; }
        public string up_28 { get; set; }
        public string low_28 { get; set; }
        public string status_28 { get; set; }
    }
}
