//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_DETAIL201806030720
    {
        public int AUTO_ID { get; set; }
        public string USER_ID { get; set; }
        public string ORDER_ID { get; set; }
        public Nullable<int> METER_ID { get; set; }
        public string RW_FLAG { get; set; }
        public string COMM_SERIAL { get; set; }
        public string COMM_FS { get; set; }
        public string COMM_BAUD { get; set; }
        public string ADDR { get; set; }
        public string BAR_CODE { get; set; }
        public string COMM_NAME { get; set; }
        public string COMMAND { get; set; }
        public string PROG_PASS { get; set; }
        public string OPER_CODE { get; set; }
        public string PROG_DATA { get; set; }
        public string READ_DATA { get; set; }
        public string BACK_FLAG { get; set; }
        public string SEND_DATA { get; set; }
        public string RECE_DATA { get; set; }
        public Nullable<int> CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string TableType { get; set; }
        public string Area { get; set; }
        public string Zlen { get; set; }
        public string Roles { get; set; }
    }
}
