//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deleteRecord
    {
        public int auto_id { get; set; }
        public string userName { get; set; }
        public string isIncludeJY { get; set; }
        public string startBarCode { get; set; }
        public string endBarCode { get; set; }
        public Nullable<int> recordCount { get; set; }
        public string backupTableName { get; set; }
        public string createDate { get; set; }
    }
}
