//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_rework
    {
        public int id { get; set; }
        public string addr { get; set; }
        public string item { get; set; }
        public string ml { get; set; }
        public string sendstr { get; set; }
        public string bz { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string backdata { get; set; }
    }
}
