//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLMS_Command
    {
        public decimal ID { get; set; }
        public string CommandName { get; set; }
        public string CommandCtrlCode { get; set; }
        public string CommandLLC { get; set; }
        public string CommandClassID { get; set; }
        public string CommandOBIS { get; set; }
        public string CommandAttribute { get; set; }
        public string CommandSNAddress { get; set; }
        public string CommandProg { get; set; }
        public string CommandReturn { get; set; }
        public string CommandType { get; set; }
        public string CommandDescription { get; set; }
        public string Status { get; set; }
        public string CommandCanRead { get; set; }
        public string CommandCanWrite { get; set; }
        public string CommandFlag { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
