//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLMS_SchemaPlan
    {
        public decimal ID { get; set; }
        public string SchemaPlanName { get; set; }
        public string SchemaID { get; set; }
        public string UserID { get; set; }
        public string CommandID { get; set; }
        public string OraderNum { get; set; }
        public Nullable<System.DateTime> PlanStartDate { get; set; }
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        public string SchemaPlanDescription { get; set; }
        public Nullable<System.DateTime> SchemaPlanCreateDate { get; set; }
        public string SchemaPlanStatus { get; set; }
    }
}
