//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_List_Info
    {
        public int ID { get; set; }
        public string MeterName { get; set; }
        public string OrderName { get; set; }
        public string startAddr { get; set; }
        public string endAddr { get; set; }
        public string num1 { get; set; }
        public string tip1 { get; set; }
        public string createId1 { get; set; }
        public string num2 { get; set; }
        public string tip2 { get; set; }
        public string createId2 { get; set; }
        public string num3 { get; set; }
        public string tip3 { get; set; }
        public string createId3 { get; set; }
        public string num4 { get; set; }
        public string tip4 { get; set; }
        public string createId4 { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    }
}
