//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class METER_DEPT_CMD_RELATION
    {
        public int ID { get; set; }
        public Nullable<int> SERIAL_NUMBER { get; set; }
        public Nullable<int> STEP_ID { get; set; }
        public string STEP_NAME { get; set; }
        public string METER_ID { get; set; }
        public string METER_NAME { get; set; }
        public string CMD_NAME { get; set; }
        public string CMD_ID { get; set; }
        public string DEPID { get; set; }
        public string DEPNAME { get; set; }
        public string CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
