//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meter_data201806060732
    {
        public int ID { get; set; }
        public string METER_NAME { get; set; }
        public string 表号 { get; set; }
        public string 录入日期 { get; set; }
        public string 命令名称 { get; set; }
        public string 命令 { get; set; }
        public string 抄表日期 { get; set; }
        public string 参数数目 { get; set; }
        public string data1 { get; set; }
        public string data2 { get; set; }
        public string data3 { get; set; }
        public string data4 { get; set; }
        public string data5 { get; set; }
        public string data6 { get; set; }
        public string data7 { get; set; }
        public string data8 { get; set; }
        public string data9 { get; set; }
        public string data10 { get; set; }
        public string data11 { get; set; }
        public string data12 { get; set; }
        public string data13 { get; set; }
        public string data14 { get; set; }
        public string data15 { get; set; }
        public string data16 { get; set; }
        public string data17 { get; set; }
        public string data18 { get; set; }
        public string data19 { get; set; }
        public string data20 { get; set; }
        public string data21 { get; set; }
        public string data22 { get; set; }
        public string data23 { get; set; }
        public string data24 { get; set; }
        public string data25 { get; set; }
        public string data26 { get; set; }
        public string data27 { get; set; }
        public string data28 { get; set; }
        public string data29 { get; set; }
        public string data30 { get; set; }
        public string data31 { get; set; }
        public string data32 { get; set; }
        public string data33 { get; set; }
        public string data34 { get; set; }
        public string data35 { get; set; }
        public string data36 { get; set; }
        public string data37 { get; set; }
        public string data38 { get; set; }
        public string data39 { get; set; }
        public string data40 { get; set; }
        public string data41 { get; set; }
        public string data42 { get; set; }
        public string data43 { get; set; }
        public string data44 { get; set; }
        public string data45 { get; set; }
        public string data46 { get; set; }
        public string data47 { get; set; }
        public string data48 { get; set; }
        public string data49 { get; set; }
        public string data50 { get; set; }
        public string data51 { get; set; }
        public string data52 { get; set; }
        public string data53 { get; set; }
        public string data54 { get; set; }
        public string data55 { get; set; }
        public string data56 { get; set; }
        public string data57 { get; set; }
        public string data58 { get; set; }
        public string data59 { get; set; }
        public string data60 { get; set; }
        public string flag { get; set; }
        public string 名称 { get; set; }
        public string USER_ID { get; set; }
        public string ORDER_ID { get; set; }
        public string 表位 { get; set; }
        public string STRTXFS { get; set; }
    }
}
