//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class METER_OPER_INFO
    {
        public int METER_OPER_ID { get; set; }
        public Nullable<int> METER_ID { get; set; }
        public Nullable<int> CMD_ID { get; set; }
        public string DEPART_ID { get; set; }
        public Nullable<int> ADD_FLAG { get; set; }
        public Nullable<int> SHOW_SIGN { get; set; }
        public Nullable<int> CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> SEQ { get; set; }
        public string ApprovedStatus { get; set; }
        public string ApprovedUser { get; set; }
    
        public virtual METER_INFO METER_INFO { get; set; }
    }
}
