//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelType
    {
        public string MType { get; set; }
        public string CREATE_ID { get; set; }
        public string CREATE_DATE { get; set; }
        public int AUTO_ID { get; set; }
    }
}
