//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QUALBACKEntities : DbContext
    {
        public QUALBACKEntities()
            : base("name=QUALBACKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C645_Command_template> C645_Command_template { get; set; }
        public DbSet<AOI_BAR_CORR_RELA> AOI_BAR_CORR_RELA { get; set; }
        public DbSet<AUTH_INFO> AUTH_INFO { get; set; }
        public DbSet<BAR_CORR_RELA> BAR_CORR_RELA { get; set; }
        public DbSet<BAR_CORR_RELA_BackUp20180609> BAR_CORR_RELA_BackUp20180609 { get; set; }
        public DbSet<BAR_CORR_RELA_Spare> BAR_CORR_RELA_Spare { get; set; }
        public DbSet<BoxInfor> BoxInfor { get; set; }
        public DbSet<BOXINFOR_DETAIL> BOXINFOR_DETAIL { get; set; }
        public DbSet<CEGONGHAO_SUCCESS_LIB> CEGONGHAO_SUCCESS_LIB { get; set; }
        public DbSet<CESHI_SUCCESS_LIB> CESHI_SUCCESS_LIB { get; set; }
        public DbSet<ClearStealingState> ClearStealingState { get; set; }
        public DbSet<CMD_DATANAME> CMD_DATANAME { get; set; }
        public DbSet<CMDINFO_NEW> CMDINFO_NEW { get; set; }
        public DbSet<CODE_RULES> CODE_RULES { get; set; }
        public DbSet<COMM_INFO> COMM_INFO { get; set; }
        public DbSet<CONTRACT_INFO> CONTRACT_INFO { get; set; }
        public DbSet<Data_Compare> Data_Compare { get; set; }
        public DbSet<DATA_TYPE> DATA_TYPE { get; set; }
        public DbSet<DataForPack> DataForPack { get; set; }
        public DbSet<DEBUG_SUCCESS_LIB> DEBUG_SUCCESS_LIB { get; set; }
        public DbSet<DEFA_INFO> DEFA_INFO { get; set; }
        public DbSet<DEPART> DEPART { get; set; }
        public DbSet<DYNA_PASS_LIB> DYNA_PASS_LIB { get; set; }
        public DbSet<ERROR_LEVEL> ERROR_LEVEL { get; set; }
        public DbSet<ERROR_TYPE> ERROR_TYPE { get; set; }
        public DbSet<InterfaceInfo> InterfaceInfo { get; set; }
        public DbSet<LIB_DATA> LIB_DATA { get; set; }
        public DbSet<METER_DEPT_CMD_RELATION> METER_DEPT_CMD_RELATION { get; set; }
        public DbSet<METER_INFO> METER_INFO { get; set; }
        public DbSet<METER_OPER_INFO> METER_OPER_INFO { get; set; }
        public DbSet<MODULE> MODULE { get; set; }
        public DbSet<Module_Oper> Module_Oper { get; set; }
        public DbSet<ORDER_METER_DEFAULT> ORDER_METER_DEFAULT { get; set; }
        public DbSet<Ori_BoxInFor> Ori_BoxInFor { get; set; }
        public DbSet<Ori_BoxInFor20131203> Ori_BoxInFor20131203 { get; set; }
        public DbSet<Pass_Url> Pass_Url { get; set; }
        public DbSet<password> password { get; set; }
        public DbSet<QRCODE_INFO> QRCODE_INFO { get; set; }
        public DbSet<STSKey> STSKey { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<SYSTEM_LOGS> SYSTEM_LOGS { get; set; }
        public DbSet<TEST_SUCCESS_LIB000> TEST_SUCCESS_LIB000 { get; set; }
        public DbSet<USER_INFO> USER_INFO { get; set; }
        public DbSet<User_Log> User_Log { get; set; }
        public DbSet<User_mes> User_mes { get; set; }
        public DbSet<User_Oper> User_Oper { get; set; }
        public DbSet<USER_ORDER_METER_RELATION> USER_ORDER_METER_RELATION { get; set; }
        public DbSet<AddrChange> AddrChange { get; set; }
        public DbSet<AddrField> AddrField { get; set; }
        public DbSet<applyNewNum> applyNewNum { get; set; }
        public DbSet<BACK_ERROR_INFO> BACK_ERROR_INFO { get; set; }
        public DbSet<BACK_ERROR_INFO_Back201510161018> BACK_ERROR_INFO_Back201510161018 { get; set; }
        public DbSet<bartemp2> bartemp2 { get; set; }
        public DbSet<BidDatas> BidDatas { get; set; }
        public DbSet<CEH_BAR_CORR_RELA> CEH_BAR_CORR_RELA { get; set; }
        public DbSet<CESHI_OUT> CESHI_OUT { get; set; }
        public DbSet<CESHI_SUCCESS_LIB201507001> CESHI_SUCCESS_LIB201507001 { get; set; }
        public DbSet<CESHI_SUCCESS_LIB20150820> CESHI_SUCCESS_LIB20150820 { get; set; }
        public DbSet<CESHI_SUCCESS_LIB20151001> CESHI_SUCCESS_LIB20151001 { get; set; }
        public DbSet<CESHI_SUCCESS_LIB20160101> CESHI_SUCCESS_LIB20160101 { get; set; }
        public DbSet<CESHI_SUCCESS_LIB20160201> CESHI_SUCCESS_LIB20160201 { get; set; }
        public DbSet<CESHI_SUCCESS_LIB20160301> CESHI_SUCCESS_LIB20160301 { get; set; }
        public DbSet<CESHI_SUCCESS_LIB20160401> CESHI_SUCCESS_LIB20160401 { get; set; }
        public DbSet<CESHI_SUCCESS_LIB20160501> CESHI_SUCCESS_LIB20160501 { get; set; }
        public DbSet<CESHI_SUCCESS_LIB20160801> CESHI_SUCCESS_LIB20160801 { get; set; }
        public DbSet<CESHI_SUCCESS_LIB20161001> CESHI_SUCCESS_LIB20161001 { get; set; }
        public DbSet<CESHI_SUCCESS_LIB20170101> CESHI_SUCCESS_LIB20170101 { get; set; }
        public DbSet<CESHI_UNINSERT> CESHI_UNINSERT { get; set; }
        public DbSet<CheckSigle> CheckSigle { get; set; }
        public DbSet<CMD_INFO> CMD_INFO { get; set; }
        public DbSet<CMD_INFO_BackUp> CMD_INFO_BackUp { get; set; }
        public DbSet<CODE_RULES_BackUp> CODE_RULES_BackUp { get; set; }
        public DbSet<comm_info20170112164117> comm_info20170112164117 { get; set; }
        public DbSet<comm_info20170323090448> comm_info20170323090448 { get; set; }
        public DbSet<comm_info20170323092920> comm_info20170323092920 { get; set; }
        public DbSet<comm_info20170323093122> comm_info20170323093122 { get; set; }
        public DbSet<comm_info20170407150341> comm_info20170407150341 { get; set; }
        public DbSet<comm_info20170408083437> comm_info20170408083437 { get; set; }
        public DbSet<comm_info20170408084336> comm_info20170408084336 { get; set; }
        public DbSet<comm_info20170408102529> comm_info20170408102529 { get; set; }
        public DbSet<comm_info20170829083512> comm_info20170829083512 { get; set; }
        public DbSet<comm_info20171005> comm_info20171005 { get; set; }
        public DbSet<comm_info20171019120721> comm_info20171019120721 { get; set; }
        public DbSet<comm_info20171023135413> comm_info20171023135413 { get; set; }
        public DbSet<comm_info20171109084010> comm_info20171109084010 { get; set; }
        public DbSet<comm_info20171113174845> comm_info20171113174845 { get; set; }
        public DbSet<comm_info20171123171855> comm_info20171123171855 { get; set; }
        public DbSet<comm_info20171123172214> comm_info20171123172214 { get; set; }
        public DbSet<comm_info20171202132744> comm_info20171202132744 { get; set; }
        public DbSet<comm_info20171202152934> comm_info20171202152934 { get; set; }
        public DbSet<comm_info20180110114032> comm_info20180110114032 { get; set; }
        public DbSet<comm_info20180131083333> comm_info20180131083333 { get; set; }
        public DbSet<comm_info20180316161227> comm_info20180316161227 { get; set; }
        public DbSet<comm_info20180316161819> comm_info20180316161819 { get; set; }
        public DbSet<comm_info20180512181557> comm_info20180512181557 { get; set; }
        public DbSet<comm_info20180516175918> comm_info20180516175918 { get; set; }
        public DbSet<comm_info20180607081754> comm_info20180607081754 { get; set; }
        public DbSet<comm_info20180614131415> comm_info20180614131415 { get; set; }
        public DbSet<comm_info20180614131733> comm_info20180614131733 { get; set; }
        public DbSet<comm_info20180614132252> comm_info20180614132252 { get; set; }
        public DbSet<comm_info20180614132331> comm_info20180614132331 { get; set; }
        public DbSet<comm_info20180614132517> comm_info20180614132517 { get; set; }
        public DbSet<CONTRACT_INFO_BackUp> CONTRACT_INFO_BackUp { get; set; }
        public DbSet<COPYCODE_INFO> COPYCODE_INFO { get; set; }
        public DbSet<Data_Compare_bak> Data_Compare_bak { get; set; }
        public DbSet<DATA_DETAIL> DATA_DETAIL { get; set; }
        public DbSet<DATA_DETAIL201710060721> DATA_DETAIL201710060721 { get; set; }
        public DbSet<DATA_DETAIL201710080721> DATA_DETAIL201710080721 { get; set; }
        public DbSet<DATA_DETAIL201710090721> DATA_DETAIL201710090721 { get; set; }
        public DbSet<DATA_DETAIL201710100721> DATA_DETAIL201710100721 { get; set; }
        public DbSet<DATA_DETAIL201710110721> DATA_DETAIL201710110721 { get; set; }
        public DbSet<DATA_DETAIL201710120722> DATA_DETAIL201710120722 { get; set; }
        public DbSet<DATA_DETAIL201710140720> DATA_DETAIL201710140720 { get; set; }
        public DbSet<DATA_DETAIL201710150720> DATA_DETAIL201710150720 { get; set; }
        public DbSet<DATA_DETAIL201710170720> DATA_DETAIL201710170720 { get; set; }
        public DbSet<DATA_DETAIL201710190720> DATA_DETAIL201710190720 { get; set; }
        public DbSet<DATA_DETAIL201710200721> DATA_DETAIL201710200721 { get; set; }
        public DbSet<DATA_DETAIL201710210721> DATA_DETAIL201710210721 { get; set; }
        public DbSet<DATA_DETAIL201710220721> DATA_DETAIL201710220721 { get; set; }
        public DbSet<DATA_DETAIL201710240721> DATA_DETAIL201710240721 { get; set; }
        public DbSet<DATA_DETAIL201710250721> DATA_DETAIL201710250721 { get; set; }
        public DbSet<DATA_DETAIL201710260721> DATA_DETAIL201710260721 { get; set; }
        public DbSet<DATA_DETAIL201710270721> DATA_DETAIL201710270721 { get; set; }
        public DbSet<DATA_DETAIL201710280721> DATA_DETAIL201710280721 { get; set; }
        public DbSet<DATA_DETAIL201710310721> DATA_DETAIL201710310721 { get; set; }
        public DbSet<DATA_DETAIL201711010721> DATA_DETAIL201711010721 { get; set; }
        public DbSet<DATA_DETAIL201711020721> DATA_DETAIL201711020721 { get; set; }
        public DbSet<DATA_DETAIL201711030721> DATA_DETAIL201711030721 { get; set; }
        public DbSet<DATA_DETAIL201711040721> DATA_DETAIL201711040721 { get; set; }
        public DbSet<DATA_DETAIL201711050722> DATA_DETAIL201711050722 { get; set; }
        public DbSet<DATA_DETAIL201711080722> DATA_DETAIL201711080722 { get; set; }
        public DbSet<DATA_DETAIL201711090722> DATA_DETAIL201711090722 { get; set; }
        public DbSet<DATA_DETAIL201711100722> DATA_DETAIL201711100722 { get; set; }
        public DbSet<DATA_DETAIL201711110722> DATA_DETAIL201711110722 { get; set; }
        public DbSet<DATA_DETAIL201711120722> DATA_DETAIL201711120722 { get; set; }
        public DbSet<DATA_DETAIL201711140722> DATA_DETAIL201711140722 { get; set; }
        public DbSet<DATA_DETAIL201711160721> DATA_DETAIL201711160721 { get; set; }
        public DbSet<DATA_DETAIL201711170721> DATA_DETAIL201711170721 { get; set; }
        public DbSet<DATA_DETAIL201711180721> DATA_DETAIL201711180721 { get; set; }
        public DbSet<DATA_DETAIL201711190721> DATA_DETAIL201711190721 { get; set; }
        public DbSet<DATA_DETAIL201711210721> DATA_DETAIL201711210721 { get; set; }
        public DbSet<DATA_DETAIL201711220721> DATA_DETAIL201711220721 { get; set; }
        public DbSet<DATA_DETAIL201711230721> DATA_DETAIL201711230721 { get; set; }
        public DbSet<DATA_DETAIL201711240721> DATA_DETAIL201711240721 { get; set; }
        public DbSet<DATA_DETAIL201711260721> DATA_DETAIL201711260721 { get; set; }
        public DbSet<DATA_DETAIL201711280722> DATA_DETAIL201711280722 { get; set; }
        public DbSet<DATA_DETAIL201711290722> DATA_DETAIL201711290722 { get; set; }
        public DbSet<DATA_DETAIL201711300722> DATA_DETAIL201711300722 { get; set; }
        public DbSet<DATA_DETAIL201712010722> DATA_DETAIL201712010722 { get; set; }
        public DbSet<DATA_DETAIL201712020722> DATA_DETAIL201712020722 { get; set; }
        public DbSet<DATA_DETAIL201712030722> DATA_DETAIL201712030722 { get; set; }
        public DbSet<DATA_DETAIL201712050722> DATA_DETAIL201712050722 { get; set; }
        public DbSet<DATA_DETAIL201712060722> DATA_DETAIL201712060722 { get; set; }
        public DbSet<DATA_DETAIL201712070722> DATA_DETAIL201712070722 { get; set; }
        public DbSet<DATA_DETAIL201712080722> DATA_DETAIL201712080722 { get; set; }
        public DbSet<DATA_DETAIL201712090722> DATA_DETAIL201712090722 { get; set; }
        public DbSet<DATA_DETAIL201712100722> DATA_DETAIL201712100722 { get; set; }
        public DbSet<DATA_DETAIL201712120720> DATA_DETAIL201712120720 { get; set; }
        public DbSet<DATA_DETAIL201712130720> DATA_DETAIL201712130720 { get; set; }
        public DbSet<DATA_DETAIL201712140720> DATA_DETAIL201712140720 { get; set; }
        public DbSet<DATA_DETAIL201712150720> DATA_DETAIL201712150720 { get; set; }
        public DbSet<DATA_DETAIL201712160720> DATA_DETAIL201712160720 { get; set; }
        public DbSet<DATA_DETAIL201712190720> DATA_DETAIL201712190720 { get; set; }
        public DbSet<DATA_DETAIL201712200720> DATA_DETAIL201712200720 { get; set; }
        public DbSet<DATA_DETAIL201712210720> DATA_DETAIL201712210720 { get; set; }
        public DbSet<DATA_DETAIL201712230720> DATA_DETAIL201712230720 { get; set; }
        public DbSet<DATA_DETAIL201712260720> DATA_DETAIL201712260720 { get; set; }
        public DbSet<DATA_DETAIL201712270720> DATA_DETAIL201712270720 { get; set; }
        public DbSet<DATA_DETAIL201712280721> DATA_DETAIL201712280721 { get; set; }
        public DbSet<DATA_DETAIL201712290721> DATA_DETAIL201712290721 { get; set; }
        public DbSet<DATA_DETAIL201801030721> DATA_DETAIL201801030721 { get; set; }
        public DbSet<DATA_DETAIL201801040721> DATA_DETAIL201801040721 { get; set; }
        public DbSet<DATA_DETAIL201801060721> DATA_DETAIL201801060721 { get; set; }
        public DbSet<DATA_DETAIL201801070721> DATA_DETAIL201801070721 { get; set; }
        public DbSet<DATA_DETAIL201801090721> DATA_DETAIL201801090721 { get; set; }
        public DbSet<DATA_DETAIL201801100721> DATA_DETAIL201801100721 { get; set; }
        public DbSet<DATA_DETAIL201801110721> DATA_DETAIL201801110721 { get; set; }
        public DbSet<DATA_DETAIL201801130722> DATA_DETAIL201801130722 { get; set; }
        public DbSet<DATA_DETAIL201801140722> DATA_DETAIL201801140722 { get; set; }
        public DbSet<DATA_DETAIL201801160722> DATA_DETAIL201801160722 { get; set; }
        public DbSet<DATA_DETAIL201801170722> DATA_DETAIL201801170722 { get; set; }
        public DbSet<DATA_DETAIL201801250721> DATA_DETAIL201801250721 { get; set; }
        public DbSet<DATA_DETAIL201801260721> DATA_DETAIL201801260721 { get; set; }
        public DbSet<DATA_DETAIL201801270722> DATA_DETAIL201801270722 { get; set; }
        public DbSet<DATA_DETAIL201801280722> DATA_DETAIL201801280722 { get; set; }
        public DbSet<DATA_DETAIL201801300722> DATA_DETAIL201801300722 { get; set; }
        public DbSet<DATA_DETAIL201801310722> DATA_DETAIL201801310722 { get; set; }
        public DbSet<DATA_DETAIL201802010722> DATA_DETAIL201802010722 { get; set; }
        public DbSet<DATA_DETAIL201802020722> DATA_DETAIL201802020722 { get; set; }
        public DbSet<DATA_DETAIL201802040722> DATA_DETAIL201802040722 { get; set; }
        public DbSet<DATA_DETAIL201802070722> DATA_DETAIL201802070722 { get; set; }
        public DbSet<DATA_DETAIL201802080722> DATA_DETAIL201802080722 { get; set; }
        public DbSet<DATA_DETAIL201802090722> DATA_DETAIL201802090722 { get; set; }
        public DbSet<DATA_DETAIL201802100722> DATA_DETAIL201802100722 { get; set; }
        public DbSet<DATA_DETAIL201803010721> DATA_DETAIL201803010721 { get; set; }
        public DbSet<DATA_DETAIL201803020721> DATA_DETAIL201803020721 { get; set; }
        public DbSet<DATA_DETAIL201803040722> DATA_DETAIL201803040722 { get; set; }
        public DbSet<DATA_DETAIL201803060722> DATA_DETAIL201803060722 { get; set; }
        public DbSet<DATA_DETAIL201803070722> DATA_DETAIL201803070722 { get; set; }
        public DbSet<DATA_DETAIL201803080722> DATA_DETAIL201803080722 { get; set; }
        public DbSet<DATA_DETAIL201803090722> DATA_DETAIL201803090722 { get; set; }
        public DbSet<DATA_DETAIL201803100722> DATA_DETAIL201803100722 { get; set; }
        public DbSet<DATA_DETAIL201803110722> DATA_DETAIL201803110722 { get; set; }
        public DbSet<DATA_DETAIL201803130722> DATA_DETAIL201803130722 { get; set; }
        public DbSet<DATA_DETAIL201803140722> DATA_DETAIL201803140722 { get; set; }
        public DbSet<DATA_DETAIL201803150720> DATA_DETAIL201803150720 { get; set; }
        public DbSet<DATA_DETAIL201803170720> DATA_DETAIL201803170720 { get; set; }
        public DbSet<DATA_DETAIL201803200720> DATA_DETAIL201803200720 { get; set; }
        public DbSet<DATA_DETAIL201803210720> DATA_DETAIL201803210720 { get; set; }
        public DbSet<DATA_DETAIL201803220720> DATA_DETAIL201803220720 { get; set; }
        public DbSet<DATA_DETAIL201803230720> DATA_DETAIL201803230720 { get; set; }
        public DbSet<DATA_DETAIL201803240720> DATA_DETAIL201803240720 { get; set; }
        public DbSet<DATA_DETAIL201803250720> DATA_DETAIL201803250720 { get; set; }
        public DbSet<DATA_DETAIL201803270720> DATA_DETAIL201803270720 { get; set; }
        public DbSet<DATA_DETAIL201803280720> DATA_DETAIL201803280720 { get; set; }
        public DbSet<DATA_DETAIL201803290720> DATA_DETAIL201803290720 { get; set; }
        public DbSet<DATA_DETAIL201803300721> DATA_DETAIL201803300721 { get; set; }
        public DbSet<DATA_DETAIL201803310721> DATA_DETAIL201803310721 { get; set; }
        public DbSet<DATA_DETAIL201804010721> DATA_DETAIL201804010721 { get; set; }
        public DbSet<DATA_DETAIL201804030721> DATA_DETAIL201804030721 { get; set; }
        public DbSet<DATA_DETAIL201804040721> DATA_DETAIL201804040721 { get; set; }
        public DbSet<DATA_DETAIL201804100721> DATA_DETAIL201804100721 { get; set; }
        public DbSet<DATA_DETAIL201804110721> DATA_DETAIL201804110721 { get; set; }
        public DbSet<DATA_DETAIL201804130721> DATA_DETAIL201804130721 { get; set; }
        public DbSet<DATA_DETAIL201804140721> DATA_DETAIL201804140721 { get; set; }
        public DbSet<DATA_DETAIL201804150721> DATA_DETAIL201804150721 { get; set; }
        public DbSet<DATA_DETAIL201804160721> DATA_DETAIL201804160721 { get; set; }
        public DbSet<DATA_DETAIL201804170721> DATA_DETAIL201804170721 { get; set; }
        public DbSet<DATA_DETAIL201804180721> DATA_DETAIL201804180721 { get; set; }
        public DbSet<DATA_DETAIL201804190721> DATA_DETAIL201804190721 { get; set; }
        public DbSet<DATA_DETAIL201804200721> DATA_DETAIL201804200721 { get; set; }
        public DbSet<DATA_DETAIL201804210721> DATA_DETAIL201804210721 { get; set; }
        public DbSet<DATA_DETAIL201804220721> DATA_DETAIL201804220721 { get; set; }
        public DbSet<DATA_DETAIL201804240722> DATA_DETAIL201804240722 { get; set; }
        public DbSet<DATA_DETAIL201804250722> DATA_DETAIL201804250722 { get; set; }
        public DbSet<DATA_DETAIL201804260722> DATA_DETAIL201804260722 { get; set; }
        public DbSet<DATA_DETAIL201804270721> DATA_DETAIL201804270721 { get; set; }
        public DbSet<DATA_DETAIL201804280721> DATA_DETAIL201804280721 { get; set; }
        public DbSet<DATA_DETAIL201804290721> DATA_DETAIL201804290721 { get; set; }
        public DbSet<DATA_DETAIL201805030721> DATA_DETAIL201805030721 { get; set; }
        public DbSet<DATA_DETAIL201805040721> DATA_DETAIL201805040721 { get; set; }
        public DbSet<DATA_DETAIL201805050721> DATA_DETAIL201805050721 { get; set; }
        public DbSet<DATA_DETAIL201805060721> DATA_DETAIL201805060721 { get; set; }
        public DbSet<DATA_DETAIL201805080721> DATA_DETAIL201805080721 { get; set; }
        public DbSet<DATA_DETAIL201805090721> DATA_DETAIL201805090721 { get; set; }
        public DbSet<DATA_DETAIL201805100721> DATA_DETAIL201805100721 { get; set; }
        public DbSet<DATA_DETAIL201805110721> DATA_DETAIL201805110721 { get; set; }
        public DbSet<DATA_DETAIL201805120721> DATA_DETAIL201805120721 { get; set; }
        public DbSet<DATA_DETAIL201805130721> DATA_DETAIL201805130721 { get; set; }
        public DbSet<DATA_DETAIL201805150721> DATA_DETAIL201805150721 { get; set; }
        public DbSet<DATA_DETAIL201805160721> DATA_DETAIL201805160721 { get; set; }
        public DbSet<DATA_DETAIL201805180722> DATA_DETAIL201805180722 { get; set; }
        public DbSet<DATA_DETAIL201805190722> DATA_DETAIL201805190722 { get; set; }
        public DbSet<DATA_DETAIL201805200722> DATA_DETAIL201805200722 { get; set; }
        public DbSet<DATA_DETAIL201805220722> DATA_DETAIL201805220722 { get; set; }
        public DbSet<DATA_DETAIL201805230722> DATA_DETAIL201805230722 { get; set; }
        public DbSet<DATA_DETAIL201805240722> DATA_DETAIL201805240722 { get; set; }
        public DbSet<DATA_DETAIL201805250722> DATA_DETAIL201805250722 { get; set; }
        public DbSet<DATA_DETAIL201805260722> DATA_DETAIL201805260722 { get; set; }
        public DbSet<DATA_DETAIL201805270722> DATA_DETAIL201805270722 { get; set; }
        public DbSet<DATA_DETAIL201805290722> DATA_DETAIL201805290722 { get; set; }
        public DbSet<DATA_DETAIL201805300722> DATA_DETAIL201805300722 { get; set; }
        public DbSet<DATA_DETAIL201805310722> DATA_DETAIL201805310722 { get; set; }
        public DbSet<DATA_DETAIL201806010723> DATA_DETAIL201806010723 { get; set; }
        public DbSet<DATA_DETAIL201806020720> DATA_DETAIL201806020720 { get; set; }
        public DbSet<DATA_DETAIL201806030720> DATA_DETAIL201806030720 { get; set; }
        public DbSet<DATA_DETAIL201806050720> DATA_DETAIL201806050720 { get; set; }
        public DbSet<DATA_DETAIL201806060720> DATA_DETAIL201806060720 { get; set; }
        public DbSet<DATA_DETAIL201806070720> DATA_DETAIL201806070720 { get; set; }
        public DbSet<DATA_DETAIL201806080720> DATA_DETAIL201806080720 { get; set; }
        public DbSet<DATA_DETAIL201806090720> DATA_DETAIL201806090720 { get; set; }
        public DbSet<DATA_DETAIL201806100720> DATA_DETAIL201806100720 { get; set; }
        public DbSet<DATA_DETAIL201806120720> DATA_DETAIL201806120720 { get; set; }
        public DbSet<DATA_DETAIL201806130720> DATA_DETAIL201806130720 { get; set; }
        public DbSet<DATA_DETAIL201806140720> DATA_DETAIL201806140720 { get; set; }
        public DbSet<DATA_DETAIL201806150720> DATA_DETAIL201806150720 { get; set; }
        public DbSet<DATA_DETAIL201806160720> DATA_DETAIL201806160720 { get; set; }
        public DbSet<DATA_DETAIL201806180721> DATA_DETAIL201806180721 { get; set; }
        public DbSet<DATA_DETAIL201806190721> DATA_DETAIL201806190721 { get; set; }
        public DbSet<DATA_DETAIL201806200721> DATA_DETAIL201806200721 { get; set; }
        public DbSet<DATA_DETAIL201806210721> DATA_DETAIL201806210721 { get; set; }
        public DbSet<DATA_DETAIL201806220721> DATA_DETAIL201806220721 { get; set; }
        public DbSet<DATA_DETAIL201806230721> DATA_DETAIL201806230721 { get; set; }
        public DbSet<DEFA_INFO_BackUp> DEFA_INFO_BackUp { get; set; }
        public DbSet<DEFA_INFO_BackUp_Save> DEFA_INFO_BackUp_Save { get; set; }
        public DbSet<deleteRecord> deleteRecord { get; set; }
        public DbSet<DepartMeter> DepartMeter { get; set; }
        public DbSet<Detail_rework> Detail_rework { get; set; }
        public DbSet<DLMS_Attribute_OBIS_Relation> DLMS_Attribute_OBIS_Relation { get; set; }
        public DbSet<DLMS_Class_OBIS_Relation> DLMS_Class_OBIS_Relation { get; set; }
        public DbSet<DLMS_Command> DLMS_Command { get; set; }
        public DbSet<DLMS_CommandSchema> DLMS_CommandSchema { get; set; }
        public DbSet<DLMS_Log> DLMS_Log { get; set; }
        public DbSet<DLMS_SchemaPlan> DLMS_SchemaPlan { get; set; }
        public DbSet<ERROR_TYPE_BackUp> ERROR_TYPE_BackUp { get; set; }
        public DbSet<FaultChildReason> FaultChildReason { get; set; }
        public DbSet<FaultMainReason> FaultMainReason { get; set; }
        public DbSet<INSTR> INSTR { get; set; }
        public DbSet<JMS> JMS { get; set; }
        public DbSet<killTask> killTask { get; set; }
        public DbSet<Material_List_Info> Material_List_Info { get; set; }
        public DbSet<Meter_data> Meter_data { get; set; }
        public DbSet<Meter_data201710141232> Meter_data201710141232 { get; set; }
        public DbSet<Meter_data201710161232> Meter_data201710161232 { get; set; }
        public DbSet<Meter_data201710170732> Meter_data201710170732 { get; set; }
        public DbSet<Meter_data201710180732> Meter_data201710180732 { get; set; }
        public DbSet<Meter_data201710190732> Meter_data201710190732 { get; set; }
        public DbSet<Meter_data201710200730> Meter_data201710200730 { get; set; }
        public DbSet<Meter_data201710210730> Meter_data201710210730 { get; set; }
        public DbSet<Meter_data201710220730> Meter_data201710220730 { get; set; }
        public DbSet<Meter_data201710240730> Meter_data201710240730 { get; set; }
        public DbSet<Meter_data201710250730> Meter_data201710250730 { get; set; }
        public DbSet<Meter_data201710260730> Meter_data201710260730 { get; set; }
        public DbSet<Meter_data201710270730> Meter_data201710270730 { get; set; }
        public DbSet<Meter_data201710280730> Meter_data201710280730 { get; set; }
        public DbSet<Meter_data201710290730> Meter_data201710290730 { get; set; }
        public DbSet<Meter_data201710310730> Meter_data201710310730 { get; set; }
        public DbSet<Meter_data201711010730> Meter_data201711010730 { get; set; }
        public DbSet<Meter_data201711020730> Meter_data201711020730 { get; set; }
        public DbSet<Meter_data201711030730> Meter_data201711030730 { get; set; }
        public DbSet<Meter_data201711040730> Meter_data201711040730 { get; set; }
        public DbSet<Meter_data201711050731> Meter_data201711050731 { get; set; }
        public DbSet<Meter_data201711070731> Meter_data201711070731 { get; set; }
        public DbSet<Meter_data201711080731> Meter_data201711080731 { get; set; }
        public DbSet<Meter_data201711090731> Meter_data201711090731 { get; set; }
        public DbSet<Meter_data201711100731> Meter_data201711100731 { get; set; }
        public DbSet<Meter_data201711110731> Meter_data201711110731 { get; set; }
        public DbSet<Meter_data201711120731> Meter_data201711120731 { get; set; }
        public DbSet<Meter_data201711140731> Meter_data201711140731 { get; set; }
        public DbSet<Meter_data201711151230> Meter_data201711151230 { get; set; }
        public DbSet<Meter_data201711160730> Meter_data201711160730 { get; set; }
        public DbSet<Meter_data201711170730> Meter_data201711170730 { get; set; }
        public DbSet<Meter_data201711180730> Meter_data201711180730 { get; set; }
        public DbSet<Meter_data201711190730> Meter_data201711190730 { get; set; }
        public DbSet<Meter_data201711210730> Meter_data201711210730 { get; set; }
        public DbSet<Meter_data201711220730> Meter_data201711220730 { get; set; }
        public DbSet<Meter_data201711230730> Meter_data201711230730 { get; set; }
        public DbSet<Meter_data201711240730> Meter_data201711240730 { get; set; }
        public DbSet<Meter_data201711250730> Meter_data201711250730 { get; set; }
        public DbSet<Meter_data201711260730> Meter_data201711260730 { get; set; }
        public DbSet<Meter_data201711280731> Meter_data201711280731 { get; set; }
        public DbSet<Meter_data201711290731> Meter_data201711290731 { get; set; }
        public DbSet<Meter_data201711300731> Meter_data201711300731 { get; set; }
        public DbSet<Meter_data201712010731> Meter_data201712010731 { get; set; }
        public DbSet<Meter_data201712020731> Meter_data201712020731 { get; set; }
        public DbSet<Meter_data201712030731> Meter_data201712030731 { get; set; }
        public DbSet<Meter_data201712050731> Meter_data201712050731 { get; set; }
        public DbSet<Meter_data201712060731> Meter_data201712060731 { get; set; }
        public DbSet<Meter_data201712070731> Meter_data201712070731 { get; set; }
        public DbSet<Meter_data201712080731> Meter_data201712080731 { get; set; }
        public DbSet<Meter_data201712090731> Meter_data201712090731 { get; set; }
        public DbSet<Meter_data201712100731> Meter_data201712100731 { get; set; }
        public DbSet<Meter_data201712120732> Meter_data201712120732 { get; set; }
        public DbSet<Meter_data201712130732> Meter_data201712130732 { get; set; }
        public DbSet<Meter_data201712140732> Meter_data201712140732 { get; set; }
        public DbSet<Meter_data201712150732> Meter_data201712150732 { get; set; }
        public DbSet<Meter_data201712160732> Meter_data201712160732 { get; set; }
        public DbSet<Meter_data201712170732> Meter_data201712170732 { get; set; }
        public DbSet<Meter_data201712190732> Meter_data201712190732 { get; set; }
        public DbSet<Meter_data201712200732> Meter_data201712200732 { get; set; }
        public DbSet<Meter_data201712210732> Meter_data201712210732 { get; set; }
        public DbSet<Meter_data201712220732> Meter_data201712220732 { get; set; }
        public DbSet<Meter_data201712230732> Meter_data201712230732 { get; set; }
        public DbSet<Meter_data201712240732> Meter_data201712240732 { get; set; }
        public DbSet<Meter_data201712260732> Meter_data201712260732 { get; set; }
        public DbSet<Meter_data201712270732> Meter_data201712270732 { get; set; }
        public DbSet<Meter_data201712280730> Meter_data201712280730 { get; set; }
        public DbSet<Meter_data201712290730> Meter_data201712290730 { get; set; }
        public DbSet<Meter_data201801021230> Meter_data201801021230 { get; set; }
        public DbSet<Meter_data201801031230> Meter_data201801031230 { get; set; }
        public DbSet<Meter_data201801040730> Meter_data201801040730 { get; set; }
        public DbSet<Meter_data201801050730> Meter_data201801050730 { get; set; }
        public DbSet<Meter_data201801061230> Meter_data201801061230 { get; set; }
        public DbSet<Meter_data201801081230> Meter_data201801081230 { get; set; }
        public DbSet<Meter_data201801090730> Meter_data201801090730 { get; set; }
        public DbSet<Meter_data201801100730> Meter_data201801100730 { get; set; }
        public DbSet<Meter_data201801110730> Meter_data201801110730 { get; set; }
        public DbSet<Meter_data201801120731> Meter_data201801120731 { get; set; }
        public DbSet<Meter_data201801130731> Meter_data201801130731 { get; set; }
        public DbSet<Meter_data201801140731> Meter_data201801140731 { get; set; }
        public DbSet<Meter_data201801160731> Meter_data201801160731 { get; set; }
        public DbSet<Meter_data201801170731> Meter_data201801170731 { get; set; }
        public DbSet<Meter_data201801241230> Meter_data201801241230 { get; set; }
        public DbSet<Meter_data201801250730> Meter_data201801250730 { get; set; }
        public DbSet<Meter_data201801260730> Meter_data201801260730 { get; set; }
        public DbSet<Meter_data201801270731> Meter_data201801270731 { get; set; }
        public DbSet<Meter_data201801280731> Meter_data201801280731 { get; set; }
        public DbSet<Meter_data201801300731> Meter_data201801300731 { get; set; }
        public DbSet<Meter_data201801310731> Meter_data201801310731 { get; set; }
        public DbSet<Meter_data201802010731> Meter_data201802010731 { get; set; }
        public DbSet<Meter_data201802021231> Meter_data201802021231 { get; set; }
        public DbSet<Meter_data201802031231> Meter_data201802031231 { get; set; }
        public DbSet<Meter_data201802060731> Meter_data201802060731 { get; set; }
        public DbSet<Meter_data201802070731> Meter_data201802070731 { get; set; }
        public DbSet<Meter_data201802080731> Meter_data201802080731 { get; set; }
        public DbSet<Meter_data201802090731> Meter_data201802090731 { get; set; }
        public DbSet<Meter_data201802100731> Meter_data201802100731 { get; set; }
        public DbSet<Meter_data201803010730> Meter_data201803010730 { get; set; }
        public DbSet<Meter_data201803020730> Meter_data201803020730 { get; set; }
        public DbSet<Meter_data201803030731> Meter_data201803030731 { get; set; }
        public DbSet<Meter_data201803040731> Meter_data201803040731 { get; set; }
        public DbSet<Meter_data201803051231> Meter_data201803051231 { get; set; }
        public DbSet<Meter_data201803060731> Meter_data201803060731 { get; set; }
        public DbSet<Meter_data201803070731> Meter_data201803070731 { get; set; }
        public DbSet<Meter_data201803080731> Meter_data201803080731 { get; set; }
        public DbSet<Meter_data201803090731> Meter_data201803090731 { get; set; }
        public DbSet<Meter_data201803100731> Meter_data201803100731 { get; set; }
        public DbSet<Meter_data201803110731> Meter_data201803110731 { get; set; }
        public DbSet<Meter_data201803130731> Meter_data201803130731 { get; set; }
        public DbSet<Meter_data201803140731> Meter_data201803140731 { get; set; }
        public DbSet<Meter_data201803150732> Meter_data201803150732 { get; set; }
        public DbSet<Meter_data201803160732> Meter_data201803160732 { get; set; }
        public DbSet<Meter_data201803170732> Meter_data201803170732 { get; set; }
        public DbSet<Meter_data201803180732> Meter_data201803180732 { get; set; }
        public DbSet<Meter_data201803200732> Meter_data201803200732 { get; set; }
        public DbSet<Meter_data201803210732> Meter_data201803210732 { get; set; }
        public DbSet<Meter_data201803220732> Meter_data201803220732 { get; set; }
        public DbSet<Meter_data201803230732> Meter_data201803230732 { get; set; }
        public DbSet<Meter_data201803240732> Meter_data201803240732 { get; set; }
        public DbSet<Meter_data201803250732> Meter_data201803250732 { get; set; }
        public DbSet<Meter_data201803270732> Meter_data201803270732 { get; set; }
        public DbSet<Meter_data201803280732> Meter_data201803280732 { get; set; }
        public DbSet<Meter_data201803290732> Meter_data201803290732 { get; set; }
        public DbSet<Meter_data201803300733> Meter_data201803300733 { get; set; }
        public DbSet<Meter_data201803310730> Meter_data201803310730 { get; set; }
        public DbSet<Meter_data201804010730> Meter_data201804010730 { get; set; }
        public DbSet<Meter_data201804030730> Meter_data201804030730 { get; set; }
        public DbSet<Meter_data201804040730> Meter_data201804040730 { get; set; }
        public DbSet<Meter_data201804050730> Meter_data201804050730 { get; set; }
        public DbSet<Meter_data201804091230> Meter_data201804091230 { get; set; }
        public DbSet<Meter_data201804110730> Meter_data201804110730 { get; set; }
        public DbSet<Meter_data201804120730> Meter_data201804120730 { get; set; }
        public DbSet<Meter_data201804130730> Meter_data201804130730 { get; set; }
        public DbSet<Meter_data201804140730> Meter_data201804140730 { get; set; }
        public DbSet<Meter_data201804150730> Meter_data201804150730 { get; set; }
        public DbSet<Meter_data201804160730> Meter_data201804160730 { get; set; }
        public DbSet<Meter_data201804170730> Meter_data201804170730 { get; set; }
        public DbSet<Meter_data201804180730> Meter_data201804180730 { get; set; }
        public DbSet<Meter_data201804190730> Meter_data201804190730 { get; set; }
        public DbSet<Meter_data201804200730> Meter_data201804200730 { get; set; }
        public DbSet<Meter_data201804210730> Meter_data201804210730 { get; set; }
        public DbSet<Meter_data201804220730> Meter_data201804220730 { get; set; }
        public DbSet<Meter_data201804240731> Meter_data201804240731 { get; set; }
        public DbSet<Meter_data201804250731> Meter_data201804250731 { get; set; }
        public DbSet<Meter_data201804260731> Meter_data201804260731 { get; set; }
        public DbSet<Meter_data201804270730> Meter_data201804270730 { get; set; }
        public DbSet<Meter_data201804280730> Meter_data201804280730 { get; set; }
        public DbSet<Meter_data201804290730> Meter_data201804290730 { get; set; }
        public DbSet<Meter_data201805030730> Meter_data201805030730 { get; set; }
        public DbSet<Meter_data201805040730> Meter_data201805040730 { get; set; }
        public DbSet<Meter_data201805050730> Meter_data201805050730 { get; set; }
        public DbSet<Meter_data201805060730> Meter_data201805060730 { get; set; }
        public DbSet<Meter_data201805080730> Meter_data201805080730 { get; set; }
        public DbSet<Meter_data201805090730> Meter_data201805090730 { get; set; }
        public DbSet<Meter_data201805100730> Meter_data201805100730 { get; set; }
        public DbSet<Meter_data201805110730> Meter_data201805110730 { get; set; }
        public DbSet<Meter_data201805120730> Meter_data201805120730 { get; set; }
        public DbSet<Meter_data201805131230> Meter_data201805131230 { get; set; }
        public DbSet<Meter_data201805150730> Meter_data201805150730 { get; set; }
        public DbSet<Meter_data201805160730> Meter_data201805160730 { get; set; }
        public DbSet<Meter_data201805170731> Meter_data201805170731 { get; set; }
        public DbSet<Meter_data201805180731> Meter_data201805180731 { get; set; }
        public DbSet<Meter_data201805190731> Meter_data201805190731 { get; set; }
        public DbSet<Meter_data201805200731> Meter_data201805200731 { get; set; }
        public DbSet<Meter_data201805220731> Meter_data201805220731 { get; set; }
        public DbSet<Meter_data201805230731> Meter_data201805230731 { get; set; }
        public DbSet<Meter_data201805240731> Meter_data201805240731 { get; set; }
        public DbSet<Meter_data201805260731> Meter_data201805260731 { get; set; }
        public DbSet<Meter_data201805280731> Meter_data201805280731 { get; set; }
        public DbSet<Meter_data201805290731> Meter_data201805290731 { get; set; }
        public DbSet<Meter_data201805301231> Meter_data201805301231 { get; set; }
        public DbSet<Meter_data201805310731> Meter_data201805310731 { get; set; }
        public DbSet<Meter_data201806010732> Meter_data201806010732 { get; set; }
        public DbSet<Meter_data201806020732> Meter_data201806020732 { get; set; }
        public DbSet<Meter_data201806030732> Meter_data201806030732 { get; set; }
        public DbSet<Meter_data201806050732> Meter_data201806050732 { get; set; }
        public DbSet<Meter_data201806060732> Meter_data201806060732 { get; set; }
        public DbSet<Meter_data201806070732> Meter_data201806070732 { get; set; }
        public DbSet<Meter_data201806080732> Meter_data201806080732 { get; set; }
        public DbSet<Meter_data201806091232> Meter_data201806091232 { get; set; }
        public DbSet<Meter_data201806100732> Meter_data201806100732 { get; set; }
        public DbSet<Meter_data201806120732> Meter_data201806120732 { get; set; }
        public DbSet<Meter_data201806130732> Meter_data201806130732 { get; set; }
        public DbSet<Meter_data201806140732> Meter_data201806140732 { get; set; }
        public DbSet<Meter_data201806150732> Meter_data201806150732 { get; set; }
        public DbSet<Meter_data201806171230> Meter_data201806171230 { get; set; }
        public DbSet<Meter_data201806181230> Meter_data201806181230 { get; set; }
        public DbSet<Meter_data201806200730> Meter_data201806200730 { get; set; }
        public DbSet<Meter_data201806210730> Meter_data201806210730 { get; set; }
        public DbSet<Meter_data201806221230> Meter_data201806221230 { get; set; }
        public DbSet<METER_INFO_BackUp> METER_INFO_BackUp { get; set; }
        public DbSet<ModelType> ModelType { get; set; }
        public DbSet<OIData> OIData { get; set; }
        public DbSet<ORDER_METER> ORDER_METER { get; set; }
        public DbSet<responsibleDepart> responsibleDepart { get; set; }
        public DbSet<silkInfo> silkInfo { get; set; }
        public DbSet<SMT_Order_Defa> SMT_Order_Defa { get; set; }
        public DbSet<StandardInfo> StandardInfo { get; set; }
        public DbSet<StarDatas> StarDatas { get; set; }
        public DbSet<Stat_Sort_Time> Stat_Sort_Time { get; set; }
        public DbSet<successForTest> successForTest { get; set; }
        public DbSet<temp> temp { get; set; }
        public DbSet<TEST_SUCCESS_LIB111> TEST_SUCCESS_LIB111 { get; set; }
        public DbSet<TEST_SUCCESS_LIB222> TEST_SUCCESS_LIB222 { get; set; }
        public DbSet<Three_Meter_Info> Three_Meter_Info { get; set; }
        public DbSet<THREE_SPEC> THREE_SPEC { get; set; }
        public DbSet<USER_INFO20150827> USER_INFO20150827 { get; set; }
        public DbSet<version> version { get; set; }
        public DbSet<Vi_Vu_VALUE> Vi_Vu_VALUE { get; set; }
        public DbSet<Voltage> Voltage { get; set; }
        public DbSet<单位> 单位 { get; set; }
        public DbSet<地区> 地区 { get; set; }
        public DbSet<密码库> 密码库 { get; set; }
        public DbSet<命令编码1> 命令编码1 { get; set; }
        public DbSet<命令标准库> 命令标准库 { get; set; }
        public DbSet<命令名称> 命令名称 { get; set; }
        public DbSet<数据格式> 数据格式 { get; set; }
        public DbSet<终端故障表> 终端故障表 { get; set; }
        public DbSet<View_BACK_ERROR_INFO> View_BACK_ERROR_INFO { get; set; }
        public DbSet<View_BAR_CORR_RELA> View_BAR_CORR_RELA { get; set; }
        public DbSet<View_CMD_INFO> View_CMD_INFO { get; set; }
        public DbSet<View_CODE_RULES> View_CODE_RULES { get; set; }
        public DbSet<View_COMM_INFO> View_COMM_INFO { get; set; }
        public DbSet<View_DATA_DETAIL> View_DATA_DETAIL { get; set; }
        public DbSet<View_DATA_DETAIL_ALL> View_DATA_DETAIL_ALL { get; set; }
        public DbSet<View_DATA_DETAIL20130805> View_DATA_DETAIL20130805 { get; set; }
        public DbSet<View_DATA_DETAIL20130907> View_DATA_DETAIL20130907 { get; set; }
        public DbSet<View_DATA_DETAIL20131026> View_DATA_DETAIL20131026 { get; set; }
        public DbSet<View_DATA_DETAIL20141016> View_DATA_DETAIL20141016 { get; set; }
        public DbSet<View_DEFA_INFO> View_DEFA_INFO { get; set; }
        public DbSet<View_DEPART> View_DEPART { get; set; }
        public DbSet<View_ERROR_TYPE> View_ERROR_TYPE { get; set; }
        public DbSet<View_ErrorCount> View_ErrorCount { get; set; }
        public DbSet<View_Meter_data> View_Meter_data { get; set; }
        public DbSet<View_Meter_data20130805> View_Meter_data20130805 { get; set; }
        public DbSet<View_Meter_data20130826> View_Meter_data20130826 { get; set; }
        public DbSet<View_Meter_data20130907> View_Meter_data20130907 { get; set; }
        public DbSet<View_Meter_data20130927> View_Meter_data20130927 { get; set; }
        public DbSet<View_Meter_data20131012> View_Meter_data20131012 { get; set; }
        public DbSet<View_Meter_data20131023> View_Meter_data20131023 { get; set; }
        public DbSet<View_Meter_data20131101> View_Meter_data20131101 { get; set; }
        public DbSet<View_METER_INFO> View_METER_INFO { get; set; }
        public DbSet<View_METER_OPER_INFO> View_METER_OPER_INFO { get; set; }
        public DbSet<View_MODULE> View_MODULE { get; set; }
        public DbSet<View_StaOutPut> View_StaOutPut { get; set; }
        public DbSet<View_StatWorkPro> View_StatWorkPro { get; set; }
        public DbSet<VW_COMM_INFO_S> VW_COMM_INFO_S { get; set; }
        public DbSet<VW_COMM_INFO_T> VW_COMM_INFO_T { get; set; }
    
        [EdmFunction("QUALBACKEntities", "f_split_str")]
        public virtual IQueryable<f_split_str_Result> f_split_str(string @string, string split)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("string", @string) :
                new ObjectParameter("string", typeof(string));
    
            var splitParameter = split != null ?
                new ObjectParameter("split", split) :
                new ObjectParameter("split", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_split_str_Result>("[QUALBACKEntities].[f_split_str](@string, @split)", stringParameter, splitParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<SP_AssStandardRate_Result> SP_AssStandardRate(string beginDate, string endDate, string departID, string orderID)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var departIDParameter = departID != null ?
                new ObjectParameter("DepartID", departID) :
                new ObjectParameter("DepartID", typeof(string));
    
            var orderIDParameter = orderID != null ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AssStandardRate_Result>("SP_AssStandardRate", beginDateParameter, endDateParameter, departIDParameter, orderIDParameter);
        }
    
        public virtual ObjectResult<SP_AssStandardRate_Test_Result> SP_AssStandardRate_Test(string beginDate, string endDate, string departID, string orderID)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var departIDParameter = departID != null ?
                new ObjectParameter("DepartID", departID) :
                new ObjectParameter("DepartID", typeof(string));
    
            var orderIDParameter = orderID != null ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AssStandardRate_Test_Result>("SP_AssStandardRate_Test", beginDateParameter, endDateParameter, departIDParameter, orderIDParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_DropTBL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DropTBL");
        }
    
        public virtual ObjectResult<SP_FaultStatistics_Result> SP_FaultStatistics(string beginDate, string endDate, string depart, string type)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var departParameter = depart != null ?
                new ObjectParameter("Depart", depart) :
                new ObjectParameter("Depart", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FaultStatistics_Result>("SP_FaultStatistics", beginDateParameter, endDateParameter, departParameter, typeParameter);
        }
    
        public virtual int SP_GetContractInfo(string oRDER_ID)
        {
            var oRDER_IDParameter = oRDER_ID != null ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GetContractInfo", oRDER_IDParameter);
        }
    
        public virtual int SP_GetContractInfoList(string oRDER_ID)
        {
            var oRDER_IDParameter = oRDER_ID != null ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GetContractInfoList", oRDER_IDParameter);
        }
    
        public virtual ObjectResult<SP_GetDatasForTestDept_Result> SP_GetDatasForTestDept(string beginTime, string endTime, Nullable<int> meterID, string orderID)
        {
            var beginTimeParameter = beginTime != null ?
                new ObjectParameter("BeginTime", beginTime) :
                new ObjectParameter("BeginTime", typeof(string));
    
            var endTimeParameter = endTime != null ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(string));
    
            var meterIDParameter = meterID.HasValue ?
                new ObjectParameter("MeterID", meterID) :
                new ObjectParameter("MeterID", typeof(int));
    
            var orderIDParameter = orderID != null ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDatasForTestDept_Result>("SP_GetDatasForTestDept", beginTimeParameter, endTimeParameter, meterIDParameter, orderIDParameter);
        }
    
        public virtual ObjectResult<SP_GetDatasForUser_Result> SP_GetDatasForUser(string dEPART_ID, string oRDER_ID, string mETER_ID, string beginDate, string endDate)
        {
            var dEPART_IDParameter = dEPART_ID != null ?
                new ObjectParameter("DEPART_ID", dEPART_ID) :
                new ObjectParameter("DEPART_ID", typeof(string));
    
            var oRDER_IDParameter = oRDER_ID != null ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(string));
    
            var mETER_IDParameter = mETER_ID != null ?
                new ObjectParameter("METER_ID", mETER_ID) :
                new ObjectParameter("METER_ID", typeof(string));
    
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDatasForUser_Result>("SP_GetDatasForUser", dEPART_IDParameter, oRDER_IDParameter, mETER_IDParameter, beginDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<SP_GetDatasForWorkshop_Result> SP_GetDatasForWorkshop(string departID, string beginTime, string endTime, Nullable<int> meterID, string orderID)
        {
            var departIDParameter = departID != null ?
                new ObjectParameter("DepartID", departID) :
                new ObjectParameter("DepartID", typeof(string));
    
            var beginTimeParameter = beginTime != null ?
                new ObjectParameter("BeginTime", beginTime) :
                new ObjectParameter("BeginTime", typeof(string));
    
            var endTimeParameter = endTime != null ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(string));
    
            var meterIDParameter = meterID.HasValue ?
                new ObjectParameter("MeterID", meterID) :
                new ObjectParameter("MeterID", typeof(int));
    
            var orderIDParameter = orderID != null ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDatasForWorkshop_Result>("SP_GetDatasForWorkshop", departIDParameter, beginTimeParameter, endTimeParameter, meterIDParameter, orderIDParameter);
        }
    
        public virtual ObjectResult<SP_GetDelayBaseData_Result> SP_GetDelayBaseData(string uSER_ID, string bEGIN_DATE, string eND_DATE)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var bEGIN_DATEParameter = bEGIN_DATE != null ?
                new ObjectParameter("BEGIN_DATE", bEGIN_DATE) :
                new ObjectParameter("BEGIN_DATE", typeof(string));
    
            var eND_DATEParameter = eND_DATE != null ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDelayBaseData_Result>("SP_GetDelayBaseData", uSER_IDParameter, bEGIN_DATEParameter, eND_DATEParameter);
        }
    
        public virtual ObjectResult<SP_GetDelayDatas_Result> SP_GetDelayDatas(string uSER_ID, string bEGIN_DATE, string eND_DATE)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var bEGIN_DATEParameter = bEGIN_DATE != null ?
                new ObjectParameter("BEGIN_DATE", bEGIN_DATE) :
                new ObjectParameter("BEGIN_DATE", typeof(string));
    
            var eND_DATEParameter = eND_DATE != null ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDelayDatas_Result>("SP_GetDelayDatas", uSER_IDParameter, bEGIN_DATEParameter, eND_DATEParameter);
        }
    
        public virtual ObjectResult<SP_GetDelayDatasOpt_Result> SP_GetDelayDatasOpt(string uSER_ID, string bEGIN_DATE, string eND_DATE)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var bEGIN_DATEParameter = bEGIN_DATE != null ?
                new ObjectParameter("BEGIN_DATE", bEGIN_DATE) :
                new ObjectParameter("BEGIN_DATE", typeof(string));
    
            var eND_DATEParameter = eND_DATE != null ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDelayDatasOpt_Result>("SP_GetDelayDatasOpt", uSER_IDParameter, bEGIN_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int SP_GetDelayDatasOpt_TEMP(string uSER_ID, string bEGIN_DATE, string eND_DATE)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var bEGIN_DATEParameter = bEGIN_DATE != null ?
                new ObjectParameter("BEGIN_DATE", bEGIN_DATE) :
                new ObjectParameter("BEGIN_DATE", typeof(string));
    
            var eND_DATEParameter = eND_DATE != null ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GetDelayDatasOpt_TEMP", uSER_IDParameter, bEGIN_DATEParameter, eND_DATEParameter);
        }
    
        public virtual int SP_GetDelayDatasOpt20141016(string uSER_ID, string bEGIN_DATE, string eND_DATE)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var bEGIN_DATEParameter = bEGIN_DATE != null ?
                new ObjectParameter("BEGIN_DATE", bEGIN_DATE) :
                new ObjectParameter("BEGIN_DATE", typeof(string));
    
            var eND_DATEParameter = eND_DATE != null ?
                new ObjectParameter("END_DATE", eND_DATE) :
                new ObjectParameter("END_DATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GetDelayDatasOpt20141016", uSER_IDParameter, bEGIN_DATEParameter, eND_DATEParameter);
        }
    
        public virtual ObjectResult<SP_GetErrorDatas_Result> SP_GetErrorDatas(Nullable<int> meterID, string orderID, string beginTime, string endTime)
        {
            var meterIDParameter = meterID.HasValue ?
                new ObjectParameter("MeterID", meterID) :
                new ObjectParameter("MeterID", typeof(int));
    
            var orderIDParameter = orderID != null ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(string));
    
            var beginTimeParameter = beginTime != null ?
                new ObjectParameter("BeginTime", beginTime) :
                new ObjectParameter("BeginTime", typeof(string));
    
            var endTimeParameter = endTime != null ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetErrorDatas_Result>("SP_GetErrorDatas", meterIDParameter, orderIDParameter, beginTimeParameter, endTimeParameter);
        }
    
        public virtual ObjectResult<SP_GetFaultReasonForDept_Result> SP_GetFaultReasonForDept(string dEPART_ID, string oRDER_ID, string mETER_ID, string beginDate, string endDate)
        {
            var dEPART_IDParameter = dEPART_ID != null ?
                new ObjectParameter("DEPART_ID", dEPART_ID) :
                new ObjectParameter("DEPART_ID", typeof(string));
    
            var oRDER_IDParameter = oRDER_ID != null ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(string));
    
            var mETER_IDParameter = mETER_ID != null ?
                new ObjectParameter("METER_ID", mETER_ID) :
                new ObjectParameter("METER_ID", typeof(string));
    
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetFaultReasonForDept_Result>("SP_GetFaultReasonForDept", dEPART_IDParameter, oRDER_IDParameter, mETER_IDParameter, beginDateParameter, endDateParameter);
        }
    
        public virtual int SP_H_DATAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_H_DATAS");
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_MainFailReason_Result> SP_MainFailReason(string beginDate, string endDate, string oRDER_ID)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var oRDER_IDParameter = oRDER_ID != null ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MainFailReason_Result>("SP_MainFailReason", beginDateParameter, endDateParameter, oRDER_IDParameter);
        }
    
        public virtual ObjectResult<SP_MainFailReason_Test_Result> SP_MainFailReason_Test(string beginDate, string endDate, string oRDER_ID)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var oRDER_IDParameter = oRDER_ID != null ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MainFailReason_Test_Result>("SP_MainFailReason_Test", beginDateParameter, endDateParameter, oRDER_IDParameter);
        }
    
        public virtual ObjectResult<SP_process_tool_Data_Result> SP_process_tool_Data(Nullable<int> id, string startDate, string endDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var startDateParameter = startDate != null ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_process_tool_Data_Result>("SP_process_tool_Data", idParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<SP_SaveIPForInData_Result> SP_SaveIPForInData(string iPAddr, string rTime)
        {
            var iPAddrParameter = iPAddr != null ?
                new ObjectParameter("IPAddr", iPAddr) :
                new ObjectParameter("IPAddr", typeof(string));
    
            var rTimeParameter = rTime != null ?
                new ObjectParameter("RTime", rTime) :
                new ObjectParameter("RTime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SaveIPForInData_Result>("SP_SaveIPForInData", iPAddrParameter, rTimeParameter);
        }
    
        public virtual int SP_SaveWorkCount(string userID, string departID, Nullable<int> workCount)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var departIDParameter = departID != null ?
                new ObjectParameter("DepartID", departID) :
                new ObjectParameter("DepartID", typeof(string));
    
            var workCountParameter = workCount.HasValue ?
                new ObjectParameter("WorkCount", workCount) :
                new ObjectParameter("WorkCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SaveWorkCount", userIDParameter, departIDParameter, workCountParameter);
        }
    
        public virtual ObjectResult<SP_SaveWorkCountC_Result> SP_SaveWorkCountC(string userID, string departID, Nullable<int> workCount, string oRDER_ID, Nullable<int> mETER_ID, string sTRDATE)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var departIDParameter = departID != null ?
                new ObjectParameter("DepartID", departID) :
                new ObjectParameter("DepartID", typeof(string));
    
            var workCountParameter = workCount.HasValue ?
                new ObjectParameter("WorkCount", workCount) :
                new ObjectParameter("WorkCount", typeof(int));
    
            var oRDER_IDParameter = oRDER_ID != null ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(string));
    
            var mETER_IDParameter = mETER_ID.HasValue ?
                new ObjectParameter("METER_ID", mETER_ID) :
                new ObjectParameter("METER_ID", typeof(int));
    
            var sTRDATEParameter = sTRDATE != null ?
                new ObjectParameter("STRDATE", sTRDATE) :
                new ObjectParameter("STRDATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SaveWorkCountC_Result>("SP_SaveWorkCountC", userIDParameter, departIDParameter, workCountParameter, oRDER_IDParameter, mETER_IDParameter, sTRDATEParameter);
        }
    
        public virtual ObjectResult<SP_SpecialCmdComValue_Result> SP_SpecialCmdComValue(string startTime, string endTime, string selectUser)
        {
            var startTimeParameter = startTime != null ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(string));
    
            var endTimeParameter = endTime != null ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(string));
    
            var selectUserParameter = selectUser != null ?
                new ObjectParameter("SelectUser", selectUser) :
                new ObjectParameter("SelectUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SpecialCmdComValue_Result>("SP_SpecialCmdComValue", startTimeParameter, endTimeParameter, selectUserParameter);
        }
    
        public virtual ObjectResult<SP_StaOutPut_Result> SP_StaOutPut(string beginDate, string endDate, string oRDER_ID)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var oRDER_IDParameter = oRDER_ID != null ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_StaOutPut_Result>("SP_StaOutPut", beginDateParameter, endDateParameter, oRDER_IDParameter);
        }
    
        public virtual int SP_StaOutPutByEmp(string beginDate, string endDate, string oRDER_ID, string depart_ID)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var oRDER_IDParameter = oRDER_ID != null ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(string));
    
            var depart_IDParameter = depart_ID != null ?
                new ObjectParameter("Depart_ID", depart_ID) :
                new ObjectParameter("Depart_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_StaOutPutByEmp", beginDateParameter, endDateParameter, oRDER_IDParameter, depart_IDParameter);
        }
    
        public virtual ObjectResult<SP_StatWorkPro_Result> SP_StatWorkPro(string beginDate, string endDate, string dep, string type)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var depParameter = dep != null ?
                new ObjectParameter("Dep", dep) :
                new ObjectParameter("Dep", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_StatWorkPro_Result>("SP_StatWorkPro", beginDateParameter, endDateParameter, depParameter, typeParameter);
        }
    
        public virtual int SP_TypeFaultStatistic(string beginDate, string endDate, string oRDER_ID)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var oRDER_IDParameter = oRDER_ID != null ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TypeFaultStatistic", beginDateParameter, endDateParameter, oRDER_IDParameter);
        }
    
        public virtual int SP_TypeFaultStatistic_Test(string beginDate, string endDate, string oRDER_ID)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var oRDER_IDParameter = oRDER_ID != null ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TypeFaultStatistic_Test", beginDateParameter, endDateParameter, oRDER_IDParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SP_WorkshopKeyProcess_Result> SP_WorkshopKeyProcess(string beginDate, string endDate, string depart)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var departParameter = depart != null ?
                new ObjectParameter("Depart", depart) :
                new ObjectParameter("Depart", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WorkshopKeyProcess_Result>("SP_WorkshopKeyProcess", beginDateParameter, endDateParameter, departParameter);
        }
    
        public virtual ObjectResult<SP_WorkshopPerHour_Result> SP_WorkshopPerHour(string beginDate)
        {
            var beginDateParameter = beginDate != null ?
                new ObjectParameter("BeginDate", beginDate) :
                new ObjectParameter("BeginDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WorkshopPerHour_Result>("SP_WorkshopPerHour", beginDateParameter);
        }
    }
}
