//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_METER_DEFAULT
    {
        public int ID { get; set; }
        public string ORDER_ID { get; set; }
        public string METER_ID { get; set; }
        public string DEPT_ID { get; set; }
        public string CMD_ID { get; set; }
        public string PROGRAM_DATA { get; set; }
        public string FUNCTION_NAME { get; set; }
        public string STANDARD_VALUE { get; set; }
        public string COMPARISON_METHOD { get; set; }
        public string MIN_VALUE { get; set; }
        public string MAX_VALUE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
