//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ori_BoxInFor20131203
    {
        public string ht_code { get; set; }
        public string b_area { get; set; }
        public string b_type { get; set; }
        public string cur_volt { get; set; }
        public string b_order { get; set; }
        public string txm_code { get; set; }
        public string box_code { get; set; }
        public string o_date { get; set; }
        public string o_operator { get; set; }
        public string VALIDATE { get; set; }
    }
}
