//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class silkInfo
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string planInfo { get; set; }
        public string typeStr { get; set; }
        public string standard { get; set; }
        public string Aera { get; set; }
        public string startBarcode { get; set; }
        public string endBarcode { get; set; }
        public string count { get; set; }
        public string createName { get; set; }
        public string updateName { get; set; }
    }
}
