//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMT_Order_Defa
    {
        public int id { get; set; }
        public string post { get; set; }
        public string depart_name { get; set; }
        public string user_name { get; set; }
        public string order_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string create_man { get; set; }
    }
}
