//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardInfo
    {
        public int Id { get; set; }
        public Nullable<int> METER_ID { get; set; }
        public string ORDER_ID { get; set; }
        public string User_ID { get; set; }
        public string Depart_ID { get; set; }
        public string CreateTime { get; set; }
        public string Command { get; set; }
        public string CommandName { get; set; }
        public string DataFormat { get; set; }
        public string StandardValue { get; set; }
        public string MaxValue { get; set; }
        public string MinValue { get; set; }
        public string State { get; set; }
        public string Approver { get; set; }
        public string PublisheTime { get; set; }
        public string ProcessTime { get; set; }
        public string ProgramData { get; set; }
        public string UpdateApprover { get; set; }
        public string UpdateTime { get; set; }
        public string UpLoadApprove { get; set; }
        public string Read { get; set; }
    }
}
