//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StarDatas
    {
        public int StarID { get; set; }
        public Nullable<int> ChkID { get; set; }
        public string Conclusion { get; set; }
        public string TestMan { get; set; }
        public string CheckMan { get; set; }
        public string CheckDate { get; set; }
        public string CheckTime { get; set; }
        public string Addr { get; set; }
    }
}
