//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_SUCCESS_LIB000
    {
        public int AUTO_ID { get; set; }
        public string ADDR { get; set; }
        public string A_1_IB { get; set; }
        public string A_05L_IB { get; set; }
        public string A_05L_Imax { get; set; }
        public string A_05L_02IB { get; set; }
        public string A_1_005IB { get; set; }
        public string B_1_IB { get; set; }
        public string B_05L_IB { get; set; }
        public string B_05L_Imax { get; set; }
        public string B_05L_02IB { get; set; }
        public string B_1_005IB { get; set; }
        public string C_1_IB { get; set; }
        public string C_05L_IB { get; set; }
        public string C_05L_Imax { get; set; }
        public string C_05L_02IB { get; set; }
        public string C_1_005IB { get; set; }
        public string Voltage { get; set; }
        public string One_current { get; set; }
        public string Two_current { get; set; }
        public Nullable<int> CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string ORDER_ID { get; set; }
        public Nullable<int> COMM_FLAG { get; set; }
        public Nullable<int> METER_ID { get; set; }
    }
}
