//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Three_Meter_Info
    {
        public string Meter { get; set; }
        public string Contract { get; set; }
        public string Metering_chip { get; set; }
        public string Wring_Way { get; set; }
        public string Vol { get; set; }
        public string Curr { get; set; }
        public string Meter_Type { get; set; }
        public string Acurr { get; set; }
        public string Meter_Const { get; set; }
        public string Vu { get; set; }
        public string Vi { get; set; }
        public string Switch { get; set; }
        public string Rate_Curr { get; set; }
        public string Max_Curr { get; set; }
        public string Star_Curr { get; set; }
        public Nullable<int> iU { get; set; }
        public Nullable<int> jU { get; set; }
        public Nullable<int> iI { get; set; }
        public Nullable<int> jI { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public Nullable<System.DateTime> Creat_Time { get; set; }
        public string Oper_ID { get; set; }
        public string DEPART_ID { get; set; }
    }
}
