//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THREE_SPEC
    {
        public int AUTO_ID { get; set; }
        public string METER_NAME { get; set; }
        public string ORDER_NAME { get; set; }
        public Nullable<int> CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string Table_Type { get; set; }
        public string Activ_Class { get; set; }
        public string Volt { get; set; }
        public string Curr { get; set; }
        public string Cons { get; set; }
        public string Vu { get; set; }
        public string Vi { get; set; }
        public string Table_Lx { get; set; }
        public string Swith_Lx { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string Rate_Curr { get; set; }
        public string Max_Curr { get; set; }
        public string Star_Curr { get; set; }
        public string iU { get; set; }
        public string jU { get; set; }
        public string iI { get; set; }
        public string jI { get; set; }
    }
}
