//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Log
    {
        public long auto_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> oper_id { get; set; }
        public Nullable<int> mod_id { get; set; }
        public Nullable<System.DateTime> oper_time { get; set; }
    }
}
