//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vi_Vu_VALUE
    {
        public int ID { get; set; }
        public string spec { get; set; }
        public string ATT7022C { get; set; }
        public string ATT7022E { get; set; }
        public string RN8302_国网_ { get; set; }
        public string RN8302_印度_ { get; set; }
        public string RN8302_南网_ { get; set; }
    }
}
