//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BAR_CORR_RELA
    {
        public string ADDR { get; set; }
        public string PCB_CODE { get; set; }
        public string PAN_CODE { get; set; }
        public string CUSTOM_CODE { get; set; }
        public string CreateName { get; set; }
        public string UpdateName { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CreatedDepartName { get; set; }
        public string UpdateDepartName { get; set; }
        public string ORDER_ID { get; set; }
        public string t { get; set; }
        public int AUTO_ID { get; set; }
    }
}
