//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Meter_data20130907
    {
        public int ID { get; set; }
        public string METER_NAME { get; set; }
        public string 表号 { get; set; }
        public string 名称 { get; set; }
        public string ORDER_ID { get; set; }
        public string 表位 { get; set; }
        public string DEPART_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string 录入日期 { get; set; }
        public string 命令 { get; set; }
        public string 抄表日期 { get; set; }
        public string data1 { get; set; }
        public string 参数数目 { get; set; }
        public string data2 { get; set; }
        public string data3 { get; set; }
        public string data4 { get; set; }
        public string data5 { get; set; }
        public string data6 { get; set; }
        public string data7 { get; set; }
        public string data8 { get; set; }
        public string data9 { get; set; }
        public string data10 { get; set; }
        public string data11 { get; set; }
        public string data12 { get; set; }
        public string data13 { get; set; }
        public string data14 { get; set; }
    }
}
