//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DEFA_INFO
    {
        public int AUTO_ID { get; set; }
        public string ORDER_ID { get; set; }
        public Nullable<int> METER_OPER_ID { get; set; }
        public string METER_NAME { get; set; }
        public string PROG_DATA { get; set; }
        public Nullable<int> TYPE_FLAG { get; set; }
        public string READ_STR { get; set; }
        public string MIN_STR { get; set; }
        public string MAX_STR { get; set; }
        public string FUNC_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string DEPART_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string t { get; set; }
        public string CMD_NAME { get; set; }
    }
}
