//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BACK_ERROR_INFO
    {
        public string ORDER_ID { get; set; }
        public string ADDR { get; set; }
        public string ADDR_IN { get; set; }
        public string SOLUTION { get; set; }
        public string REPAIR_TYPE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string USER_NAME { get; set; }
        public string DEPART_NAME { get; set; }
        public string ERROR_NAME { get; set; }
        public string METER_NAME { get; set; }
        public string t { get; set; }
        public int AUTO_ID { get; set; }
    }
}
