//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_StatWorkPro
    {
        public string 部门 { get; set; }
        public string 单三相 { get; set; }
        public Nullable<int> C2013_01 { get; set; }
        public Nullable<int> C2013_02 { get; set; }
        public Nullable<int> C2013_03 { get; set; }
        public Nullable<int> C2013_04 { get; set; }
        public Nullable<int> C2013_05 { get; set; }
        public Nullable<int> C2013_06 { get; set; }
        public Nullable<int> C2013_07 { get; set; }
        public Nullable<int> C2013_08 { get; set; }
        public Nullable<int> C2013_09 { get; set; }
        public Nullable<int> C2013_10 { get; set; }
        public Nullable<int> C2013_11 { get; set; }
        public Nullable<int> C2013_12 { get; set; }
        public Nullable<int> C2014_01 { get; set; }
        public Nullable<int> C2014_02 { get; set; }
        public Nullable<int> C2014_03 { get; set; }
        public Nullable<int> C2014_04 { get; set; }
        public Nullable<int> C2014_05 { get; set; }
        public Nullable<int> C2014_06 { get; set; }
        public Nullable<int> C2014_07 { get; set; }
        public Nullable<int> C2014_08 { get; set; }
        public Nullable<int> C2014_09 { get; set; }
        public Nullable<int> C2014_10 { get; set; }
        public Nullable<int> C2014_11 { get; set; }
        public Nullable<int> C2014_12 { get; set; }
        public Nullable<int> C2015_01 { get; set; }
        public Nullable<int> C2015_02 { get; set; }
        public Nullable<int> C2015_03 { get; set; }
        public Nullable<int> C2015_04 { get; set; }
        public Nullable<int> C2015_05 { get; set; }
        public Nullable<int> C2015_06 { get; set; }
        public Nullable<int> C2015_07 { get; set; }
        public Nullable<int> C2015_08 { get; set; }
        public Nullable<int> C2015_09 { get; set; }
        public Nullable<int> C2015_10 { get; set; }
        public Nullable<int> C2015_11 { get; set; }
        public Nullable<int> C2015_12 { get; set; }
        public Nullable<int> C2016_01 { get; set; }
        public Nullable<int> C2016_02 { get; set; }
        public Nullable<int> C2016_03 { get; set; }
        public Nullable<int> C2016_04 { get; set; }
        public Nullable<int> C2016_05 { get; set; }
        public Nullable<int> C2016_06 { get; set; }
        public Nullable<int> C2016_07 { get; set; }
        public Nullable<int> C2016_08 { get; set; }
        public Nullable<int> C2016_09 { get; set; }
        public Nullable<int> C2016_10 { get; set; }
        public Nullable<int> C2016_11 { get; set; }
        public Nullable<int> C2016_12 { get; set; }
    }
}
