//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MODULE
    {
        public int AUTO_ID { get; set; }
        public string MOD_NAME { get; set; }
        public string SHOW_TYPE { get; set; }
        public string FORM_NAME { get; set; }
        public string FORM_PATH { get; set; }
        public string USER_NAME { get; set; }
        public string DEPART_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string t { get; set; }
    }
}
