//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ErrorCount
    {
        public string 部门 { get; set; }
        public Nullable<decimal> C485不通 { get; set; }
        public Nullable<decimal> 按键坏 { get; set; }
        public Nullable<decimal> 背光灯不亮 { get; set; }
        public Nullable<decimal> 编程键坏 { get; set; }
        public Nullable<decimal> 标牌变形 { get; set; }
        public Nullable<decimal> 标牌掉 { get; set; }
        public Nullable<decimal> 标牌字迹不清 { get; set; }
        public Nullable<decimal> 表内有异物 { get; set; }
        public Nullable<decimal> 不出值 { get; set; }
        public Nullable<decimal> 不工作 { get; set; }
        public Nullable<decimal> 不计电量 { get; set; }
        public Nullable<decimal> 不能初始化_不总清_ { get; set; }
        public Nullable<decimal> 不认卡 { get; set; }
        public Nullable<decimal> 参数错 { get; set; }
        public Nullable<decimal> 侧翻盖掉 { get; set; }
        public Nullable<decimal> 灯偏 { get; set; }
        public Nullable<decimal> 底壳变形 { get; set; }
        public Nullable<decimal> 底壳裂 { get; set; }
        public Nullable<decimal> 电池失压 { get; set; }
        public Nullable<decimal> 电量错 { get; set; }
        public Nullable<decimal> 电流端子坏 { get; set; }
        public Nullable<decimal> 电容碎 { get; set; }
        public Nullable<decimal> 端钮坏 { get; set; }
        public Nullable<decimal> 蜂鸣器不响 { get; set; }
        public Nullable<decimal> 缝隙大 { get; set; }
        public Nullable<decimal> 辅助端子坏 { get; set; }
        public Nullable<decimal> 复检 { get; set; }
        public Nullable<decimal> 功率超 { get; set; }
        public Nullable<decimal> 光耦漏焊 { get; set; }
        public Nullable<decimal> 红外不通 { get; set; }
        public Nullable<decimal> 继电器不动作 { get; set; }
        public Nullable<decimal> 卡扣紧_斜 { get; set; }
        public Nullable<decimal> 开盖_端钮_错 { get; set; }
        public Nullable<decimal> 零线超 { get; set; }
        public Nullable<decimal> 脉冲异常 { get; set; }
        public Nullable<decimal> 密封圈外漏 { get; set; }
        public Nullable<decimal> 耐压不合格 { get; set; }
        public Nullable<decimal> 其他 { get; set; }
        public Nullable<decimal> 缺划 { get; set; }
        public Nullable<decimal> 日计时超差 { get; set; }
        public Nullable<decimal> 上电无显 { get; set; }
        public Nullable<decimal> 时钟电池电压超 { get; set; }
        public Nullable<decimal> 事件错 { get; set; }
        public Nullable<decimal> 视窗划伤 { get; set; }
        public Nullable<decimal> 视窗有膜 { get; set; }
        public Nullable<decimal> 视窗脏_水印 { get; set; }
        public Nullable<decimal> 跳闸_报警灯不亮_暗_ { get; set; }
        public Nullable<decimal> 停电不唤醒 { get; set; }
        public Nullable<decimal> 外观不合格 { get; set; }
        public Nullable<decimal> 无反向 { get; set; }
        public Nullable<decimal> 无该表信息 { get; set; }
        public Nullable<decimal> 无脉冲 { get; set; }
        public Nullable<decimal> 无秒信号 { get; set; }
        public Nullable<decimal> 无铅封底座 { get; set; }
        public Nullable<decimal> 无预埋键 { get; set; }
        public Nullable<decimal> 误差超差 { get; set; }
        public Nullable<decimal> 显示弱 { get; set; }
        public Nullable<decimal> 响表 { get; set; }
        public Nullable<decimal> 液晶碎 { get; set; }
        public Nullable<decimal> 液晶斜 { get; set; }
        public Nullable<decimal> 液晶有黑点 { get; set; }
        public Nullable<decimal> 液晶脏污 { get; set; }
        public Nullable<decimal> 预埋件高 { get; set; }
        public Nullable<decimal> 罩壳螺丝低 { get; set; }
    }
}
