//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 命令编码1
    {
        public string 命令编码 { get; set; }
        public string 数据项名称 { get; set; }
        public string 数据长度 { get; set; }
        public string 数据格式 { get; set; }
        public string 读 { get; set; }
        public string 写 { get; set; }
        public string 命令模式 { get; set; }
        public string 命令类别 { get; set; }
        public string 命令分类 { get; set; }
        public string 单位 { get; set; }
    }
}
