//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 命令标准库
    {
        public string 命令 { get; set; }
        public string 名称 { get; set; }
        public string 长度 { get; set; }
        public string 块标志 { get; set; }
        public string 读写 { get; set; }
        public string 掩码 { get; set; }
        public string 标识 { get; set; }
        public string 命令分类 { get; set; }
        public string 简称 { get; set; }
        public string 时间 { get; set; }
        public string 字段数 { get; set; }
        public string fd_js1 { get; set; }
        public string fd_js2 { get; set; }
        public string fd_js3 { get; set; }
        public string fd_js4 { get; set; }
        public string fd_js5 { get; set; }
        public string fd_js6 { get; set; }
        public string fd_js7 { get; set; }
        public string fd_js8 { get; set; }
        public string fd_js9 { get; set; }
        public string fd_js10 { get; set; }
        public string fd_js11 { get; set; }
        public string fd_js12 { get; set; }
        public string fd_js13 { get; set; }
        public string fd_js14 { get; set; }
        public string fd_js15 { get; set; }
        public string fd_js16 { get; set; }
        public string fd_js17 { get; set; }
        public string fd_js18 { get; set; }
        public string fd_js19 { get; set; }
        public string fd_js20 { get; set; }
        public string fd_len1 { get; set; }
        public string fd_len2 { get; set; }
        public string fd_len3 { get; set; }
        public string fd_len4 { get; set; }
        public string fd_len5 { get; set; }
        public string fd_len6 { get; set; }
        public string fd_len7 { get; set; }
        public string fd_len8 { get; set; }
        public string fd_len9 { get; set; }
        public string fd_len10 { get; set; }
        public string fd_len11 { get; set; }
        public string fd_len12 { get; set; }
        public string fd_len13 { get; set; }
        public string fd_len14 { get; set; }
        public string fd_len15 { get; set; }
        public string fd_len16 { get; set; }
        public string fd_len17 { get; set; }
        public string fd_len18 { get; set; }
        public string fd_len19 { get; set; }
        public string fd_len20 { get; set; }
        public string fd_len21 { get; set; }
        public string fd_len22 { get; set; }
        public string fd_len23 { get; set; }
        public string fd_len24 { get; set; }
        public string fd_len25 { get; set; }
        public string fd_len26 { get; set; }
        public string fd_len27 { get; set; }
        public string fd_len28 { get; set; }
        public string fd_len29 { get; set; }
        public string fd_len30 { get; set; }
        public string fd_len31 { get; set; }
        public string fd_len32 { get; set; }
        public string fd_len33 { get; set; }
        public string fd_len34 { get; set; }
        public string fd_len35 { get; set; }
        public string fd_len36 { get; set; }
        public string fd_len37 { get; set; }
        public string fd_len38 { get; set; }
        public string fd_len39 { get; set; }
        public string fd_len40 { get; set; }
        public string fd_len41 { get; set; }
        public string fd_len42 { get; set; }
        public string fd_len43 { get; set; }
        public string fd_len44 { get; set; }
        public string fd_len45 { get; set; }
        public string fd_len46 { get; set; }
        public string fd_len47 { get; set; }
        public string fd_len48 { get; set; }
        public string fd_len49 { get; set; }
        public string fd_len50 { get; set; }
        public string fd_len51 { get; set; }
        public string fd_len52 { get; set; }
        public string fd_len53 { get; set; }
        public string fd_len54 { get; set; }
        public string fd_len55 { get; set; }
        public string fd_len56 { get; set; }
        public string fd_len57 { get; set; }
        public string fd_len58 { get; set; }
        public string fd_len59 { get; set; }
        public string fd_len60 { get; set; }
        public string fd_xsfs1 { get; set; }
        public string fd_xsfs2 { get; set; }
        public string fd_xsfs3 { get; set; }
        public string fd_xsfs4 { get; set; }
        public string fd_xsfs5 { get; set; }
        public string fd_xsfs6 { get; set; }
        public string fd_xsfs7 { get; set; }
        public string fd_xsfs8 { get; set; }
        public string fd_xsfs9 { get; set; }
        public string fd_xsfs10 { get; set; }
        public string fd_xsfs11 { get; set; }
        public string fd_xsfs12 { get; set; }
        public string fd_xsfs13 { get; set; }
        public string fd_xsfs14 { get; set; }
        public string fd_xsfs15 { get; set; }
        public string fd_xsfs16 { get; set; }
        public string fd_xsfs17 { get; set; }
        public string fd_xsfs18 { get; set; }
        public string fd_xsfs19 { get; set; }
        public string fd_xsfs20 { get; set; }
        public string fd_xsfs21 { get; set; }
        public string fd_xsfs22 { get; set; }
        public string fd_xsfs23 { get; set; }
        public string fd_xsfs24 { get; set; }
        public string fd_xsfs25 { get; set; }
        public string fd_xsfs26 { get; set; }
        public string fd_xsfs27 { get; set; }
        public string fd_xsfs28 { get; set; }
        public string fd_xsfs29 { get; set; }
        public string fd_xsfs30 { get; set; }
        public string fd_xsfs31 { get; set; }
        public string fd_xsfs32 { get; set; }
        public string fd_xsfs33 { get; set; }
        public string fd_xsfs34 { get; set; }
        public string fd_xsfs35 { get; set; }
        public string fd_xsfs36 { get; set; }
        public string fd_xsfs37 { get; set; }
        public string fd_xsfs38 { get; set; }
        public string fd_xsfs39 { get; set; }
        public string fd_xsfs40 { get; set; }
        public string fd_xsfs41 { get; set; }
        public string fd_xsfs42 { get; set; }
        public string fd_xsfs43 { get; set; }
        public string fd_xsfs44 { get; set; }
        public string fd_xsfs45 { get; set; }
        public string fd_xsfs46 { get; set; }
        public string fd_xsfs47 { get; set; }
        public string fd_xsfs48 { get; set; }
        public string fd_xsfs49 { get; set; }
        public string fd_xsfs50 { get; set; }
        public string fd_xsfs51 { get; set; }
        public string fd_xsfs52 { get; set; }
        public string fd_xsfs53 { get; set; }
        public string fd_xsfs54 { get; set; }
        public string fd_xsfs55 { get; set; }
        public string fd_xsfs56 { get; set; }
        public string fd_xsfs57 { get; set; }
        public string fd_xsfs58 { get; set; }
        public string fd_xsfs59 { get; set; }
        public string fd_xsfs60 { get; set; }
        public string CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_ID { get; set; }
        public string UPDATE_NAME { get; set; }
        public string 是否比较 { get; set; }
        public int AUTO_ID { get; set; }
        public string ProgData { get; set; }
    }
}
