//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 密码库
    {
        public string 表号 { get; set; }
        public string 密码 { get; set; }
        public string 标志 { get; set; }
        public string 导入日期 { get; set; }
        public string 使用日期 { get; set; }
    }
}
