//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 终端故障表
    {
        public int 序号 { get; set; }
        public string 时间 { get; set; }
        public string 型号 { get; set; }
        public string 规格 { get; set; }
        public string 车间 { get; set; }
        public string 表号 { get; set; }
        public string 地区 { get; set; }
        public string 不合格现象描述 { get; set; }
        public string 检验员 { get; set; }
        public string 修理原因 { get; set; }
        public string 返修人员 { get; set; }
        public string 备注 { get; set; }
    }
}
